### ISSUE TITLE
[Question] 如何启用bash_aliases里自定义的命令？

### ISSUE THREAD

**Issue by Galaxy-Husky** [x-cmd/x-cmd#102]
Hi,
安装x-cmd之后，使用之前bash_aliases里自定义的命令会显示“command not found”。
如何可以启用？

**Comment by curry798** [comment]
@Galaxy-Husky Hi！你是指 ~/.bashrc 里面的自定义命令吗？

**Comment by Galaxy-Husky** [comment]
> @Galaxy-Husky Hi！你是指 ~/.bashrc 里面的自定义命令吗？

我是在文件`~/.bash_aliases`里定义的，如图：
![Snipaste_2024-11-11_11-43-18](https://github.com/user-attachments/assets/fe83f449-1987-474d-8615-a390e87fa089)。
当我运行`setproxy`之后，就显示找不到命令。

还有一个问题是安装之后原来系统的一些缩写命令，例如`ll`, `la`也失效了，是正常的表现吗？

**Comment by edwinjhlee** [comment]
> > @Galaxy-Husky Hi！你是指 ~/.bashrc 里面的自定义命令吗？
> 
> 我是在文件`~/.bash_aliases`里定义的，如图： ![Snipaste_2024-11-11_11-43-18](https://private-user-images.githubusercontent.com/18464121/384772677-fe83f449-1987-474d-8615-a390e87fa089.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyOTg5ODksIm5iZiI6MTczMTI5ODY4OSwicGF0aCI6Ii8xODQ2NDEyMS8zODQ3NzI2NzctZmU4M2Y0NDktMTk4Ny00NzRkLTg2MTUtYTM5MGU4N2ZhMDg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDA0MTgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4MDM0MWNlNjYyOGQxOTBmNTFkNjNmMTlhMjA4N2Q0NWM3MTFlYmE4ZDJlNDNjNzlkOTFiMWY5NDgxMTNkYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Pf9r0ycM-yd8z23LkaK5BQQiap2wV3Kl9KmRKGpQ8oI)。 当我运行`setproxy`之后，就显示找不到命令。
> 
> 还有一个问题是安装之后原来系统的一些缩写命令，例如`ll`, `la`也失效了，是正常的表现吗？

不正常。x-cmd 并不会覆盖这些命令。

你打开 ~/.bashrc 和 ~/.bash_profile，找到 有注释 x-cmd 的那一行，试一下把它 注释掉，看在不加载 x-cmd 的情况下，这些问题是否解决。 -- 以此确认 x-cmd 是否对此有影响。

**Comment by edwinjhlee** [comment]
不过，你要注意一下，你的 bashrc 和 bash_profile 是否有 加载 `~/.bash_aliases`

https://unix.stackexchange.com/questions/347178/bash-aliases-vs-alias-command

**Comment by Galaxy-Husky** [comment]
> > > @Galaxy-Husky Hi！你是指 ~/.bashrc 里面的自定义命令吗？
> > 
> > 
> > 我是在文件`~/.bash_aliases`里定义的，如图： ![Snipaste_2024-11-11_11-43-18](https://private-user-images.githubusercontent.com/18464121/384772677-fe83f449-1987-474d-8615-a390e87fa089.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyOTg5ODksIm5iZiI6MTczMTI5ODY4OSwicGF0aCI6Ii8xODQ2NDEyMS8zODQ3NzI2NzctZmU4M2Y0NDktMTk4Ny00NzRkLTg2MTUtYTM5MGU4N2ZhMDg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDA0MTgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4MDM0MWNlNjYyOGQxOTBmNTFkNjNmMTlhMjA4N2Q0NWM3MTFlYmE4ZDJlNDNjNzlkOTFiMWY5NDgxMTNkYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Pf9r0ycM-yd8z23LkaK5BQQiap2wV3Kl9KmRKGpQ8oI)。 当我运行`setproxy`之后，就显示找不到命令。
> > 还有一个问题是安装之后原来系统的一些缩写命令，例如`ll`, `la`也失效了，是正常的表现吗？
> 
> 不正常。x-cmd 并不会覆盖这些命令。
> 
> 你打开 ~/.bashrc 和 ~/.bash_profile，找到 有注释 x-cmd 的那一行，试一下把它 注释掉，看在不加载 x-cmd 的情况下，这些问题是否解决。 -- 以此确认 x-cmd 是否对此有影响。

我先是根据 #7 卸载了x-cmd。然后ssh连接后无法自动运行bashrc，发现bash_profile里 x-cmd 的一行没删除，而且没有其它内容。所以我的系统里本身应该是没有bash_profile，默认运行的profile。

我在bash_profile里加上了
```
if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi
```
再安装x-cmd，就一切正常了。

希望可以在官网文档中更新卸载教程~

**Comment by edwinjhlee** [comment]
好的 ～ GLHF
