### ISSUE TITLE
[REC] kyanos

### ISSUE THREAD

**Issue by edwinjhlee** [x-cmd/x-cmd#108]
## Website

https://github.com/hengyoush/kyanos

## Screenshot

![image](https://github.com/user-attachments/assets/1d629c45-7671-41af-9396-b203d291da5c)

## Ready to be included in [x-cmd pkg](https://x-cmd.com/pkg) ?

YES

## How to install

Download from the release

https://github.com/hengyoush/kyanos/releases/tag/v1.4.0

!! We will review and put it into [x install recipes](https://x-cmd.com/install).

## TLDR

```bash
# Provide a TLDR like example to help us understand
# Don't hesitate ~ The more the better !!!

# Filter by pid
kyanos watch --pids 1234

# Filter by container id
kyanos watch --container-id abc

# Filter by Redis key
kyanos watch redis --keys my-key1,my-key2

# Filter by response byte size
kyanos watch --resp-size 10000
```

##  Highlights

- Discuss the advantages of this tool: performant, provide official static build
- Stories about this tool:
- Discuss the disadvantages of this tool.

**Comment by lunrenyi** [comment]
kyanos has been added to the package.
```sh
x pkg update
x env use kyanos
```

**Comment by edwinjhlee** [comment]
Introduction document will be here:

https://x-cmd.com/pkg/kyanos
