### ISSUE TITLE
[REC] gosop

### ISSUE THREAD

**Issue by edwinjhlee** [x-cmd/x-cmd#110]
## Website

https://github.com/ProtonMail/gosop

## Ready to be included in [x-cmd pkg](https://x-cmd.com/pkg) ?

YES

## How to install

```
mkdir -p $GOPATH/src/github.com/ProtonMail/
cd $GOPATH/src/github.com/ProtonMail/
git clone git@github.com:ProtonMail/gosop.git && cd gosop
go install
```

## TLDR

```bash
# Provide a TLDR like example to help us understand
# Don't hesitate ~ The more the better !!!

# <desc-1>
<command-1>

# <desc-2>
<command-2>

# <desc-3>
<command-3>
```

## Highlights

- Discuss the advantages of this tool: 
   - cross platform
   - provided by proton mail

- Related:
   - https://github.com/ProtonMail/gosop/issues/29
   - https://github.com/ProtonMail/gosop/pull/36

**Comment by edwinjhlee** [comment]
gosop is ready ~~~ 

https://github.com/ProtonMail/gosop/releases/tag/v1.1.0

**Comment by lunrenyi** [comment]
- Added to pkg
    ```sh
    x pkg udpate
    x env use termscp
    ```

**Comment by edwinjhlee** [comment]
The introduction document will be here:

https://x-cmd.com/pkg/gosop
