### ISSUE TITLE
[BUG] Crash in x.elv on startup

### ISSUE THREAD

**Issue by iandol** [x-cmd/x-cmd#111]
**Describe the bug**

A recent update is causing my rc.elv startup to crash with this error:

```
Exception: bash exited with 1
  /Users/ian/.config/elvish/lib/x.elv:101:16-88:     var fp = ( bash $___X_CMD_ELV_RC_XBIN pkg sphere populate get_link_source_dir $name )
  /Users/ian/.config/elvish/lib/x.elv:112:5-53:     ___x_cmd___rcelv_addpython___pkg    python      0
  /Users/ian/.config/elvish/lib/x.elv:144:5-30:     ___x_cmd___rcelv_addpython
  /Users/ian/.config/elvish/rc.elv:104:9-14: 	use x; x:init
```

The failure is line 101 which runs a bash script; I'm not quite sure what the bash failure is...

I have commented out line 144 to stop this running as a workaround.

**System (please complete the following information):**
 - Version: x7 sum: 995ba3dc5ac1fba
 - Shell: elv
 - OS: Darwin
 - Arch: arm64

**Comment by qiakai** [comment]
Fixed. You can update to version x7.
```
x upgrade x7
```

**Comment by edwinjhlee** [comment]
I guess you are using x7 ~ We try to optimize the startup latency for all non-posix shells ~

**Comment by iandol** [comment]
thanks, fixed!
