### ISSUE TITLE
[REC] lazysql

### ISSUE THREAD

**Issue by edwinjhlee** [x-cmd/x-cmd#112]
## Website

https://github.com/jorgerojas26/lazysql

## Screenshot

![image](https://github.com/user-attachments/assets/8edf9506-fa5d-403a-9476-0cd9c487fb43)

## Ready to be included in [x-cmd pkg](https://x-cmd.com/pkg) ?

YES

## How to install

```
go install github.com/jorgerojas26/lazysql@latest
```

## TLDR

```bash
# Provide a TLDR like example to help us understand
# Don't hesitate ~ The more the better !!!

# <desc-1>
lazysql

# <desc-2>
<command-2>

# <desc-3>
<command-3>
```

## Highlights

- Discuss the advantages of this tool: amazing tui
- Stories about this tool:
- Discuss the disadvantages of this tool.

**Comment by lunrenyi** [comment]
- Added to pkg
    ```sh
    x pkg udpate
    x env use termscp
    ```

**Comment by edwinjhlee** [comment]
Introduction document will be here:

https://x-cmd.com/pkg/lazysql
