### ISSUE TITLE
[BUG] x ncdu 无法在mac osx下使用 | [mod=ncdu] [v0.4.14]

### ISSUE THREAD

**Issue by limars874** [x-cmd/x-cmd#113]
**Describe the bug**
x ncdu 无法在在我的mac osx下使用，输出错误大意是找不到对应的二进制包？

**System (please complete the following information):**
 - Version: v0.4.13
 - Shell: Zsh
 - OS: macOS Ventura 13.3.1
 - Arch: amd64

**Screenshots**
输出如下：
```zsh
➜ x ncdu              
- E|pkg: Not found pkg [name=ncdu] [version=v2.3.0] information data
- E|pkg: Not found pkg [name=ncdu] [version=v2.3.0] information data
- E|pkg: Perhaps the platform is NOT supported your OS or ARCH - "darwin/x64" ----> osman/ncdu
- E|pkg: Failed to add darwin/x64 'ncdu v2.3.0'
- E|pkg: |
    Install ncdu v2.3.0 failed
```
然后我搜了下，brew能安装ncdu，便使用brew安装了ncdu，直接运行ncdu没有问题。我看我们文档说明是如果本地有相同命令会自动调用。结果输入x ncdu还是上面一样的提示。请问这个正常吗？

**Comment by edwinjhlee** [comment]
你好，感谢你给我们提 issue ～


---

> 如果本地有相同命令会自动调用

你分析得对。这是不正常的。我刚看了一下代码，发现这里的逻辑在版本判断上出了问题。我们最近在赶着发布 v0.4.14, 顺便可以把这个问题解决了。

---

至于 ncdu 不提供了 mac build 的问题，我们现在没有足够的精力去编译所有的工具。等后面我们有时间将会提供。


---


另外，我刚发现 pixi 提供了 x64 这个软件包，但只提供 1.6 的版本。所以，可能最后还是要 x-cmd pkg 来编译提供。

**Comment by edwinjhlee** [comment]
@limars874 你好，这个问题已然解决。如果还有相关的问题，请随时开 issue 。

本次并未解决 mac amd64 的问题，仅解决了优先调用本地 ncdu 命令。

要提供 mac amd64 的问题需要编译工作，短期内并无精力解决；现阶段只能让用户采用 brew 来安装。
