### ISSUE TITLE
[BUG] x jina reader 无法使用 | [mod=jina] [v0.4.14]

### ISSUE THREAD

**Issue by limars874** [x-cmd/x-cmd#114]
**Describe the bug**
已配置apikey，x embed等可用，但 x jina reader 无法使用，报错意思是不正确的bear token。
我看了下源码，应该是reader方法没有夹带apikey作为token请求。
猜测是官方api有所改动，在源码里面硬编码一个bear token之后就能用了。
可惜对shell不太懂，完全看不懂embed他们是怎么拿到cfg里面的apikey的，不然就提个PR了。

**System (please complete the following information):**
 - Version:  v0.4.13
 - Shell: Zsh
 - OS: macOS Ventura 13.3.1
 - Arch: amd64

**Screenshots**
```
x jina reader x-cmd.com       
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ STDIN
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ {"data":null,"code":401,"name":"AuthenticationFailedError","status":40102,"message":"Invalid bearer token","readableMessage":"Authenticatio
       │ nFailedError: Invalid bearer token"}
───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


```

**Comment by curry798** [comment]
你好~ 在我这边并不需要 API key 也能使用 reader  -- 我猜测可能是因为  我还有免费额度。
我们稍后将会 fix 这个问题。

**Comment by edwinjhlee** [comment]
fixed at https://www.x-cmd.com/v/0.4.14/#jina

I am closing this issue ~ If problems occured, feel free to reopen.
