### ISSUE TITLE
docker中没有找到x命令

### ISSUE THREAD

**Issue by llody55** [x-cmd/x-cmd#12]
想在alpine:latest镜像中使用RUN eval "$(wget -O- https://get.x-cmd.com)" 安装x命令并构建出镜像，但是没有x命令呢？

**Comment by edwinjhlee** [comment]
你好 ～

这是 dockerfile 的特性问题。

# 问题一

```bash
From alpine

RUN eval "$(wget -O- https://get.x-cmd.com)" && x version

# 这是可以运行的
RUN . $HOME/.x-cmd.root/X; x version

# 找不到 x-cmd
RUN x version
```

因为 RUN 本身是采用非 interactive 方式执行 shell，不会 `source .$HOME/.x-cmd.root/X`


# 问题二

```bash
From alpine
RUN eval "$(wget -O- https://get.x-cmd.com)"
```

采用上述 Dockerfile 创建镜像后，仍然无法在打开 alpine 的 shell （ash） 直接使用 x-cmd。

这是因为，alpine 的 ash 哪怕在 默认 交互模块下，也不会 加载 .shinit 文件（你可以理解为 等同于 .bashrc 和 .zshrc 和 .kshrc)
必须要指定一个环境变量 ENV='<.shinit>位置'

例如:

```bash
docker run -e ENV=/root/.shinit --rm -it a
```

---

这件事有点复杂。的确存在入侵性更强的方法，例如把 x-cmd 放到 /bin，或者 改 PATH；但我认为这样入侵性太强。

我们一开始也创建了 x-cmd 的 docker image，但是我们还是倾向于，用户应该是在 使用 docker run/exe 的时候，才马上以用户态来安装；而不是在 镜像中内置 x-cmd -- 尤其是 x-cmd 还处于 快速 迭代当中。

关于如何更好在 docker 使用 x-cmd，我们其实在 docker 模块（未对外文档化）做了一些工作，例如:

- `x docker run -x <用户参数>`

这个时候，我们会往镜像的用户文件夹放 x-cmd 所要的文件，并在设置好环境变量，让打开的 shell 的 x-cmd 即处于可用状态。

不过，上述功能未正式发布，考虑到现在有用户有这方面的需求，我们会考虑在后面把这项功能正式发布。

**Comment by edwinjhlee** [comment]
如果你是想用 docker alpine 镜像，你可以试试：

x docker alp
或者
**xd alp**

我经常 `xd alp` 来快速测试 alpine ash 的一些特性。

**Comment by llody55** [comment]
感谢解惑，我尝试了你说的方法，确实可行，我做这个工具箱容器，其实就是希望可以一键拉起一个可用的工具箱。请问有没有计划做一个离线的使用方式，因为在有些环境下，不允许开放网络，这个工具软件的安装会是一个比较大的问题。
![image](https://github.com/x-cmd/x-cmd/assets/9710645/68b4a7a9-61bb-4956-907a-6fe7da806b12)

**Comment by edwinjhlee** [comment]
> @edwinjhlee 感谢解惑，我尝试了你说的方法，确实可行，但是仅限于x86架构成功了,在arm64架构下，这种方法就失效了，我做这个工具箱容器，其实就是希望可以一键拉起一个可用的工具箱。请问有没有计划做一个离线的使用方式，因为在有些环境下，不允许开放网络，这个工具软件的安装会是一个比较大的问题。 ![image](https://private-user-images.githubusercontent.com/9710645/328358728-68b4a7a9-61bb-4956-907a-6fe7da806b12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNjAwNDIsIm5iZiI6MTcxNTA1OTc0MiwicGF0aCI6Ii85NzEwNjQ1LzMyODM1ODcyOC02OGI0YTdhOS02MWJiLTQ5NTYtOTA3YS02ZmU3ZGE4MDZiMTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDdUMDUyOTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWVjOWMwODg1NjIyMzBiOWUwMTA4YTUxMDU4OTRjMDFmNTY2ZGU5ZjgyY2Y0NmY3MWVhNTI2ZDBjNWY1M2NkZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CpU0zV6NLHaOcUsTGI7XQ7FUWRKIQsUdVCNyMGLAXR0) ![image](https://private-user-images.githubusercontent.com/9710645/328359842-e95b4582-4391-43cb-9046-ae53a6861709.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNjAwNDIsIm5iZiI6MTcxNTA1OTc0MiwicGF0aCI6Ii85NzEwNjQ1LzMyODM1OTg0Mi1lOTViNDU4Mi00MzkxLTQzY2ItOTA0Ni1hZTUzYTY4NjE3MDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDdUMDUyOTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTlkY2MwNzgxZTQxMTg2YmRmY2ZhNWNlNWQ4MDMxZWU0NDJkYTNmZmJiZTIxZTdmY2Q4ZWE3ZWQ0MTFjZmExYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SY9qjM1DUoep3XEsCQKDnqO10e1mOFLLjn823oEm7Ac)

命令打错了，是 x version 不是 v version

**Comment by edwinjhlee** [comment]
> @edwinjhlee 感谢解惑，我尝试了你说的方法，确实可行，但是仅限于x86架构成功了,在arm64架构下，这种方法就失效了，我做这个工具箱容器，其实就是希望可以一键拉起一个可用的工具箱。请问有没有计划做一个离线的使用方式，因为在有些环境下，不允许开放网络，这个工具软件的安装会是一个比较大的问题。 ![image](https://private-user-images.githubusercontent.com/9710645/328358728-68b4a7a9-61bb-4956-907a-6fe7da806b12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNjAwNDIsIm5iZiI6MTcxNTA1OTc0MiwicGF0aCI6Ii85NzEwNjQ1LzMyODM1ODcyOC02OGI0YTdhOS02MWJiLTQ5NTYtOTA3YS02ZmU3ZGE4MDZiMTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDdUMDUyOTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWVjOWMwODg1NjIyMzBiOWUwMTA4YTUxMDU4OTRjMDFmNTY2ZGU5ZjgyY2Y0NmY3MWVhNTI2ZDBjNWY1M2NkZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CpU0zV6NLHaOcUsTGI7XQ7FUWRKIQsUdVCNyMGLAXR0) ![image](https://private-user-images.githubusercontent.com/9710645/328359842-e95b4582-4391-43cb-9046-ae53a6861709.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNjAwNDIsIm5iZiI6MTcxNTA1OTc0MiwicGF0aCI6Ii85NzEwNjQ1LzMyODM1OTg0Mi1lOTViNDU4Mi00MzkxLTQzY2ItOTA0Ni1hZTUzYTY4NjE3MDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDdUMDUyOTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTlkY2MwNzgxZTQxMTg2YmRmY2ZhNWNlNWQ4MDMxZWU0NDJkYTNmZmJiZTIxZTdmY2Q4ZWE3ZWQ0MTFjZmExYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SY9qjM1DUoep3XEsCQKDnqO10e1mOFLLjn823oEm7Ac)

这个问题我是这么看：
1. x-cmd 等稳定版后，提供 docker image 是 水到渠成，所以离线版问题不大
2. 但是 x-cmd 最重要的功能是庞大是 不断更新 pkg / install 库，现在有 500 多个 pkg（5种平台），不可能都离线
3. 关于在内网计算机使用 x-cmd，我的计划是在 ssh 上提供 安装和发射 x-cmd pkg 的功能。

3 的解决思路是，你在 本地计算机可以联外网，远程服务器不能连外网，本地计算机能过直接把 远程服务器所需要的 pkg 安装文件用 ssh 发射过去，这样帮助 远程服务器 使用 x-cmd 的 pkg 功能。


现阶段我们还是得先把 x-cmd 的功能完善，以及 推广起来。上述工作我们这三年一直都有留意，也逐渐一个清晰的解决思路。

**Comment by llody55** [comment]
好的，建议离线包以后可以通过指定目录就能自动安装的话，那是最好了，或者还有其他方式。

**Comment by zint99** [comment]
@edwinjhlee 请问现在是否已有“内网使用 x-cmd 的产品流程”的相关支持和教程？

**Comment by edwinjhlee** [comment]
> [@edwinjhlee](https://github.com/edwinjhlee) 请问现在是否已有“内网使用 x-cmd 的产品流程”的相关支持和教程？

我们会在后面的版本开始试用 allinone 安装包, 应该在 年前发布.

大约在年后会开始使用 ssh infuse 机制, 即通过 ssh 来给 内网主机安装 x-cmd .

我们在这个议题比较谨慎, 另外, 这个议题 还将直接影响了 后面我们如何解决 在 root 上安装, 以及 多用户如何尽量 share x-cmd 安装包的问题. 所以 不得不 慎之又慎.


另外, 这个安装仅包括 x-cmd 的  shell 功能, 包括传统命令 shell 模块 增强, theme, 命令补全 之类的. 

我们的方案暂时不能按需安装 pkg ; 或者 换句话说, 类似方案需要在 年后一个季度才会尝试实现.

**Comment by edwinjhlee** [comment]
我还想强调一下, x-cmd 现在主要在 用户空间 上使用, 而不急于提供 root 安装. 

我认为, 更改 root 管理的文件夹 是一件 非常严肃的事情, Linux 发行版很多, 版本细微区别不少, 再加上 不同系统环境 管理策略不一样.  所有这些都会导致可能的故障.

所以, 尽管我们已经基本实现 类似的功能, 会做比较久的测试. 并先行在 x7 和 alpha 版在小部分用户群内推广.

**Comment by zint99** [comment]
> 我还想强调一下, x-cmd 现在主要在 用户空间 上使用, 而不急于提供 root 安装 -- 因为后者的风险.
> 
> 我认为, 更改 root 管理的文件夹 是一件 非常严肃的事情, Linux 发行版很多, 版本细微区别不少, 再加上 不同系统环境 管理策略不一样. 所有这些都会导致超出开发者认知的故障.
> 
> 所以, 尽管我们已经基本实现 类似的功能, 会做比较久的测试. 并先行在 x7 和 alpha 版在小部分用户群内推广.
> 
> 尽管 x-cmd 的 AGPL 协议中有 No waranty 条款, 但还是尽量避免给用户添加麻烦.

感谢回复，会保持关注
