### ISSUE TITLE
[BUG] x upgrade forces me into zsh in an automated script | [mod=elv] [v0.4.15] [get.x-cmd.com]

### ISSUE THREAD

**Issue by iandol** [x-cmd/x-cmd#122]
**Describe the bug**

I run an automatic update using an elvish script every few days, and my command to update x-cmd looks like this (`cmds:if-external` just checks if a program is installed and runs the lambda if it is):

```elvish
cmds:if-external x { echo (styled "\n---> Update 文 x-cmd\n" bold bg-color5); x upgrade; x elv --setup mod }
```

The problem is most of the time x-cmd forces me into zsh:

```
---> Update 文 x-cmd

- I|x: Upgrading x-cmd version => x7
  more:
    url: https://get.x-cmd.com/x7
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   297  100   297    0     0    243      0  0:00:01  0:00:01 --:--:--   243
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1770  100  1770    0     0   2503      0 --:--:-- --:--:-- --:--:--  2507
- I|x: Already exists: /Users/ian/.x-cmd.root/v/x7
From https://codeberg.org/x-cmd/x7
 * branch            main       -> FETCH_HEAD
Already up to date.
- I|x: Running x boot init
- W|x: Current version is already x7
- I|x: Already installed in /Users/ian/.shinit
- I|x: Already installed in /Users/ian/.bashrc
- I|x: Already installed in /Users/ian/.bash_profile
- I|x: Already installed in /Users/ian/.zshrc
- I|x: Tip to setup x-cmd in tcsh
  more:
    cmd:                   x tcsh --setup
    cmd: ~/.x-cmd.root/bin/x tcsh --setup
- I|x: Updating the resource package indexes ...
  more:
    cmd: x pkg update
    tips: If it fails, or is interrupted, you can run it manually later.
- I|pkg: Update PKG resource
- I|pkg: Download v0.1.1.tar.gz form https://oss.resource.x-cmd.com/x-cmd/pkg/dist/v0.1.1.tar.gz
- I|pkg: Download v0.1.1_hash.txt from https://oss.resource.x-cmd.com/x-cmd/pkg/dist/v0.1.1_hash.txt
- I|pkg: Update the v0.1.1.tar.gz success
- I|advise: Update x-cmd advise
- I|advise: Download all.tar.xz from https://oss.resource.x-cmd.com/releases/advise/v0.0.3/all.tar.xz
- I|x: Initialization SUCCESS
- I|x: x-cmd detected in current shell env. Opening a new shell to avoid collision.
```

This blocks my upgrade completely, and not sure why but trying to exit zsh totally hangs my terminal session (kitty).

**System (please complete the following information):**
 - Version: x7 a702524dbdc70e1
 - Shell: elvish
 - OS: Darwin
 - Arch: arm64

**Expected behavior**
Some option to not force exiting into a different shell and breaking my automated script.

**Comment by edwinjhlee** [comment]
It seams we messed up handling the elvish scenario. I will add an exeception in the installation script.

**Comment by edwinjhlee** [comment]
Hi @iandol ~

Have you tried update x-cmd/x7 recently? This bug should be fixed days ago.

We welcome your feedbacks.  The next version v0.4.15 will be released in the next week.

**Comment by iandol** [comment]
Still have this problem:

```
---> Update 文 x-cmd

- I|x: Upgrading x-cmd version => x7
  more:
    url: https://get.x-cmd.com/x7
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   297  100   297    0     0    405      0 --:--:-- --:--:-- --:--:--   404
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1884  100  1884    0     0   3499      0 --:--:-- --:--:-- --:--:--  3501
- I|x: Already exists: /Users/ian/.x-cmd.root/v/x7
From https://codeberg.org/x-cmd/x7
 * branch            main       -> FETCH_HEAD
Already up to date.
- I|x: Running x boot init
- W|x: Current version is already x7
- I|x: Already installed in /Users/ian/.shinit
- I|x: Already installed in /Users/ian/.bashrc
- I|x: Already installed in /Users/ian/.bash_profile
- I|x: Already installed in /Users/ian/.zshrc
- I|x: Tip to setup x-cmd in tcsh
  more:
    cmd:                   x tcsh --setup
    cmd: ~/.x-cmd.root/bin/x tcsh --setup
- I|x: Tip to setup x-cmd in elvish
  more:
    cmd:                   x elv  --setup
    cmd: ~/.x-cmd.root/bin/x elv  --setup
- I|x: Updating the resource package indexes ...
  more:
    cmd: x pkg update
    tips: If it fails, or is interrupted, you can run it manually later.
- I|pkg: Update PKG resource
- I|pkg: Download v0.1.1.tar.gz form https://oss.resource.x-cmd.com/x-cmd/pkg/dist/v0.1.1.tar.gz
- I|pkg: Download v0.1.1_hash.txt from https://oss.resource.x-cmd.com/x-cmd/pkg/dist/v0.1.1_hash.txt
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to oss.resource.x-cmd.com:443 
- E|pkg: Download v0.1.1_hash.txt failed
- E|pkg: Update the v0.1.1.tar.gz failed
- I|x: Initialization SUCCESS
- I|x: x-cmd detected in current shell env. Opening a new shell to avoid collision.
```

**Comment by edwinjhlee** [comment]
<img width="1405" alt="image" src="https://github.com/user-attachments/assets/d2b0b484-5069-4245-a14b-c4bf44366f7d">

That's wiered. Mine is OK ...

I will take a look at it.

**Comment by iandol** [comment]
Maybe you are calling from `zsh`? I am running `elvish`, and run a function that checks is `x` is installed and then runs the update, so I imagine the `env` will be quite different:

https://codeberg.org/iandol/dotfiles/src/branch/main/aliases.elv#L335

**Comment by edwinjhlee** [comment]
I locate the problem.

In elvish when x-cmd is source, calling x = calling the external script named ___x_cmdexe_exp

However, when x-cmd is not sourced, calling x equals calling the external script named x

We assume user will only invoke x-cmd after the x-cmd is source.

I am adding a line of code to temporarily fix this problem. 

We plan to clean up the external scripts later ( maybe in v0.5.0 ). Recently, we've encountered various issues in different situations( fzf, non-posix shells ... ) when invoking the external x-cmd. To prevent disrupting the environments, we introduced different external scripts for each situation. which increases the difficulty of maintainance dramatically.

**Comment by edwinjhlee** [comment]
You can upgrade x7 now to see whether it is fixed.

**Comment by iandol** [comment]
It doesn't jump into `zsh` anymore, but the update now just hangs, cannot use ctrl+c or ctrl+d to stop what it is doing:

```---> Update 文 x-cmd

- I|x: Upgrading x-cmd version => x7
  more:
    url: https://get.x-cmd.com/x7
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   297  100   297    0     0     91      0  0:00:03  0:00:03 --:--:--    91
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1884  100  1884    0     0   1628      0  0:00:01  0:00:01 --:--:--  1629
- I|x: Already exists: /Users/ian/.x-cmd.root/v/x7
From https://codeberg.org/x-cmd/x7
 * branch            main       -> FETCH_HEAD
Already up to date.
- I|x: Running x boot init
- W|x: Current version is already x7
- I|x: Already installed in /Users/ian/.shinit
- I|x: Already installed in /Users/ian/.bashrc
- I|x: Already installed in /Users/ian/.bash_profile
- I|x: Already installed in /Users/ian/.zshrc
- I|x: Tip to setup x-cmd in tcsh
  more:
    cmd:                   x tcsh --setup
    cmd: ~/.x-cmd.root/bin/x tcsh --setup
- I|x: Tip to setup x-cmd in elvish
  more:
    cmd:                   x elv  --setup
    cmd: ~/.x-cmd.root/bin/x elv  --setup
- I|x: Updating the resource package indexes ...
  more:
    cmd: x pkg update
    tips: If it fails, or is interrupted, you can run it manually later.
- I|pkg: Update PKG resource
- I|pkg: Download v0.1.1.tar.gz form https://oss.resource.x-cmd.com/x-cmd/pkg/dist/v0.1.1.tar.gz
- I|pkg: Download v0.1.1_hash.txt from https://oss.resource.x-cmd.com/x-cmd/pkg/dist/v0.1.1_hash.txt
- I|pkg: Update the v0.1.1.tar.gz success
- I|advise: Update x-cmd advise
- I|advise: Download all.tar.xz from https://oss.resource.x-cmd.com/releases/advise/v0.0.3/all.tar.xz
- I|x: Initialization SUCCESS
- I|x: This installation/upgrade is performed by an external call, so the interactive shell for the new version will not automatically open.

[hanged]
```

**Comment by edwinjhlee** [comment]
That's wiered. The logging line should be the last line of execution code. Let's me double check the whole process.

<img width="1142" alt="image" src="https://github.com/user-attachments/assets/94b16539-290a-43c7-b51b-4e71f7fc2f64">

**Comment by edwinjhlee** [comment]
I cannot reproduce this issue in my computer.
Everything works as expected ...

I once suspect `x elv --setup mod` is the problem. But it also works fine ... 

https://codeberg.org/iandol/dotfiles/src/branch/main/aliases.elv#L335

---

Just in case, what is the output of `which x` in your elvish environment ?

**Comment by edwinjhlee** [comment]
Aha. I reproduce the problem ... I am not 100% sure we can solve it ... Because it is so wierd.

The original code below will hang

```elvish
echo (styled "\n---> Update 文 x-cmd\n" bold bg-color5); x upgrade; x elv --setup mod
```

I also try adding ; at the end of the code, still hang.

But this would not hang:

```elvish
echo (styled "\n---> Update 文 x-cmd\n" bold bg-color5); x upgrade; 
<output>

x elv --setup mod
<output>
```


That also hangs:

![Uploading image.png…]()

**Comment by edwinjhlee** [comment]
I narrow down the case. This will also hang ...

```
x version; x version;
```

**Comment by edwinjhlee** [comment]
That might be the problem of bash-3.2 ~

bash 3.2 is an ancient version of bash. Due to the license issue, the macos don't update the bash3 to bash4/5. They plans to use zsh to replace bash However, we can understand the reason why they still insist using bash 3 as /bin/sh because we also encounter some wired bugs in zsh.

Recently we do find more bugs in bash-3 involving interactive mode. It seems it is an relevant issue.

**Comment by edwinjhlee** [comment]
I don't know what to do to bypass this problem elegantly. Bu we believe we can always find a way out.

**Comment by edwinjhlee** [comment]
It seems I blame bash by mistake... It is a problem that only can be reproduced in elvish.

I am going to post an issue in elvish repo.

nushell, fish shell, zsh works fine.

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/9c3bf60c-68ad-4a8e-a859-0dbd3200a817">

**Comment by edwinjhlee** [comment]
@iandol 

Please help me reproduce this in your environment in the issue in elvish official repo. 

https://github.com/elves/elvish/issues/1866

**Comment by edwinjhlee** [comment]
@iandol 

For your case, before we finally come up a general solution or just elivish release a new version to address this issue, you could bypass it in this way:

```bash
___x_cmdexe upgrade; ___x_cmdexe elv --setup mod
```

**Comment by iandol** [comment]
Thanks!!! Indeed bash freezes at 100%

<img width="805" alt="image" src="https://github.com/user-attachments/assets/b8b61755-29f8-45c1-8d3d-657b87b4ae38">

Let me check the elvish issue and I'll also check on discord.

**Comment by iandol** [comment]
Can I install a new bash with pixi as another workaround? Maybe you hardcode to use system bash?

**Comment by edwinjhlee** [comment]
Hi Ian, if there is no other problem, maybe we could close this issue.

I have created an issue to follow elvish hang up problem.

https://github.com/x-cmd/x-cmd/issues/130

**Comment by iandol** [comment]
OK, thanks for the debugging!
