### ISSUE TITLE
[DOC] install/dblab 文档链接错误

### ISSUE THREAD

**Issue by limars874** [x-cmd/x-cmd#123]
## Url

[https://x-cmd.com/install/dblab](https://cn.x-cmd.com/install/dblab)

## Screenshot
这个dblab的homepage链接现在是 https://sparanoid.com/lab/7z/
应为 https://dblab.danvergara.com/ 或者https://github.com/danvergara/dblab

**Comment by lunrenyi** [comment]
感谢你的反馈！

**Comment by edwinjhlee** [comment]
官网已然修改，如果有问题，可重开或者新开 issue ～

谢谢反馈 ～ GLHF ～
