### ISSUE TITLE
[x advise] ssh hostname autocomplete not work

### ISSUE THREAD

**Issue by HopeCollector** [x-cmd/x-cmd#13]
**Describe the bug**
create ssh config in ~/.ssh/config and set "HOST" to something like "server1"
relogin, then tap "ssh ser<TAB>" nothing happend, didnot autocomplete the "ser" to "server1"

**To Reproduce**
1. create ssh config if u donot have, set the `HOST` to anything like "server1"
2. relogin
3. tap "ssh ser<TAB>"

**Expected behavior**
after pressed <TAB>, "ser" should be autocompleted to "server1"

**System (please complete the following information):**
 - Version: 
        .0ddd9b28
        version: v0.3.5
        date: "2024-04-20 16:34:06+0000"
        sum: 0ddd9b28fe7c1e3f8cb00b3b0690ca7f55713eed59ba00d593e604e957ea840ae14ea0178505aecee8818bc61f920de6166626eae36af4f022a2690345543d1d
 - Shell: bash
 - OS: Ubuntu22.04
 - Arch: amd64

**Comment by edwinjhlee** [comment]
Ok. Instead of considering as a bug, it is more like a feature for ssh completion.

We will look into it. Thank you.

**Comment by Zhengqbbb** [comment]
1. Currently, our SSH completion function still needs some time for improvement. 
2. In the latest version, we have introduced the `rm` subcmd in the advise module to remove the completion for a specified command. 
3. After running it, it will not replace the system or manually introduced custom completion functions:
---

```sh
x upgrade
x advise man rm x-cmd ssh
# Need to start a new session because the previous completion function has already been loaded
zsh
ssh ser<Tab>
```

---
If we improve the SSH completion function in the future, I will update and follow up on this ISSUE. 
Thank you for pointing it out and for your support.

https://github.com/x-cmd/x-cmd/assets/40693636/893b4482-bfd6-48ab-865a-18ead8450fac

**Comment by edwinjhlee** [comment]
I just find out a way to implement it by reading ssh man document ...

This feature will be release in the next version, which is scheduled to release on Sunday.

**Comment by edwinjhlee** [comment]
This issue is resolved. Now x-cmd can provide hostnames.

Thanks for your support ~~~
