### ISSUE TITLE
[BUG] pkg nmap nping doesn't works on linux arm64

### ISSUE THREAD

**Issue by edwinjhlee** [x-cmd/x-cmd#139]
**Describe the bug**

pkg nmap nping doesn't works on linux arm64

To provide such build, x-cmd needs to compile its own nmap/nping.

**Screenshots**

**To Reproduce**

x env use nmap
x env use nping

**Expected behavior**

**Additional context**

**Comment by lunrenyi** [comment]
Already fixed.
```bash
x pkg udpate 
x env use nmap
x env use nping
```
