### ISSUE TITLE
["BUG"] command "x" error

### ISSUE THREAD

**Issue by Eutopia-wf** [x-cmd/x-cmd#14]
I just run cmd "x upgrade"

stderror output:
x
gawk: /home/wf/.x-cmd.root/v/.3aa426a6/mod/tui/lib/comp/share.awk:259: function tui_parse_width_num(w, col, default, min, max){
gawk: /home/wf/.x-cmd.root/v/.3aa426a6/mod/tui/lib/comp/share.awk:259:                                      ^ syntax error
gawk: /home/wf/.x-cmd.root/v/.3aa426a6/mod/tui/lib/comp/share.awk:261:     if ((default != "") && (w <= 0))    w = default
gawk: /home/wf/.x-cmd.root/v/.3aa426a6/mod/tui/lib/comp/share.awk:261:          ^ syntax error
gawk: /home/wf/.x-cmd.root/v/.3aa426a6/mod/tui/lib/comp/share.awk:261:     if ((default != "") && (w <= 0))    w = default
gawk: /home/wf/.x-cmd.root/v/.3aa426a6/mod/tui/lib/comp/share.awk:261:                         ^ syntax error
gawk: /home/wf/.x-cmd.root/v/.3aa426a6/mod/tui/lib/comp/share.awk:261:     if ((default != "") && (w <= 0))    w = default
gawk: /home/wf/.x-cmd.root/v/.3aa426a6/mod/tui/lib/comp/share.awk:261:                                         ^ syntax error
gawk: /home/wf/.x-cmd.root/v/.3aa426a6/mod/tui/lib/comp/share.awk:262:     else if ((min != "") && (w < min) ) w = min
gawk: /home/wf/.x-cmd.root/v/.3aa426a6/mod/tui/lib/comp/share.awk:262:                                           ^ syntax error
gawk: /home/wf/.x-cmd.root/v/.3aa426a6/mod/tui/lib/comp/share.awk:263:     else if ((max != "") && (w > max) ) w = max
gawk: /home/wf/.x-cmd.root/v/.3aa426a6/mod/tui/lib/comp/share.awk:263:                                           ^ syntax error
gawk: /home/wf/.x-cmd.root/v/.3aa426a6/mod/tui/lib/comp/share.awk:265:     return int(w)
gawk: /home/wf/.x-cmd.root/v/.3aa426a6/mod/tui/lib/comp/share.awk:265:                  ^ unexpected newline or end of string

x se search "how to use jq"
gawk: /home/wf/.x-cmd.root/v/.3aa426a6/mod/tui/lib/comp/share.awk:259: function tui_parse_width_num(w, col, default, min, max){
gawk: /home/wf/.x-cmd.root/v/.3aa426a6/mod/tui/lib/comp/share.awk:259:                                      ^ syntax error
gawk: /home/wf/.x-cmd.root/v/.3aa426a6/mod/tui/lib/comp/share.awk:261:     if ((default != "") && (w <= 0))    w = default
gawk: /home/wf/.x-cmd.root/v/.3aa426a6/mod/tui/lib/comp/share.awk:261:          ^ syntax error
gawk: /home/wf/.x-cmd.root/v/.3aa426a6/mod/tui/lib/comp/share.awk:261:     if ((default != "") && (w <= 0))    w = default
gawk: /home/wf/.x-cmd.root/v/.3aa426a6/mod/tui/lib/comp/share.awk:261:                         ^ syntax error
gawk: /home/wf/.x-cmd.root/v/.3aa426a6/mod/tui/lib/comp/share.awk:261:     if ((default != "") && (w <= 0))    w = default
gawk: /home/wf/.x-cmd.root/v/.3aa426a6/mod/tui/lib/comp/share.awk:261:                                         ^ syntax error
gawk: /home/wf/.x-cmd.root/v/.3aa426a6/mod/tui/lib/comp/share.awk:262:     else if ((min != "") && (w < min) ) w = min
gawk: /home/wf/.x-cmd.root/v/.3aa426a6/mod/tui/lib/comp/share.awk:262:                                           ^ syntax error
gawk: /home/wf/.x-cmd.root/v/.3aa426a6/mod/tui/lib/comp/share.awk:263:     else if ((max != "") && (w > max) ) w = max
gawk: /home/wf/.x-cmd.root/v/.3aa426a6/mod/tui/lib/comp/share.awk:263:                                           ^ syntax error
gawk: /home/wf/.x-cmd.root/v/.3aa426a6/mod/tui/lib/comp/share.awk:265:     return int(w)
gawk: /home/wf/.x-cmd.root/v/.3aa426a6/mod/tui/lib/comp/share.awk:265:                  ^ unexpected newline or end of string

**Comment by edwinjhlee** [comment]
I am very very sorry for this bug.

It turns out the gawk 4.2.1 uses 'default' as a reserve word, and we use it as a parameter name.

```bash
function tui_parse_width_num(w, col, default, min, max){
```

I am still investigating why we didn't find this bug before we release this version.

We originally plan to release a new version tomorrow. But now I am thinking I might probably release this new version today to address this bug and also introduced new models -- gpt-4o and gemini-1.5.


Thank you for reporting this bug.

**Comment by edwinjhlee** [comment]
It turns out all of our gawk testing environments is upgraded to gawk 5.*
And now there is no testing environment for gawk 4 .

This is a big oversight on testing.

**Comment by edwinjhlee** [comment]
We just release v0.3.7

We might probably fix the bug.
It is quiet strange we can not repoduce it in gawk. Although we know the default is the reserved words.

Please `x upgrade` and give us feedback.

Thank you.

---

There is also gpt-4o , gemini 1.5 , jina-search and gtb(gutenberg)  in this release.
