### ISSUE TITLE
[REC] skopeo

### ISSUE THREAD

**Issue by edwinjhlee** [x-cmd/x-cmd#140]
## Ready to be included in [x-cmd pkg](https://x-cmd.com/pkg) ?

YES or NO

## How to install

```bash
x skopeo --help # dirctly used in x-cmd

x pixi use skopeo

apt install skopeo
scoop install skopeo
```

https://github.com/containers/skopeo/blob/main/install.md

!! We will review and put it into [x install recipes](https://x-cmd.com/install).

## TLDR

```bash
# Provide a TLDR like example to help us understand
# Don't hesitate ~ The more the better !!!

# <desc-1>
<command-1>

# <desc-2>
<command-2>

# <desc-3>
<command-3>
```

## Highlights

- Discuss the advantages of this tool.
- Stories about this tool:
- Discuss the disadvantages of this tool.

**Comment by curry798** [comment]
skopeo has been added to install:

```bash
x install skopeo
```
