### ISSUE TITLE
[BUG] xxx is not a valid file

### ISSUE THREAD

**Issue by skinhc** [x-cmd/x-cmd#144]
在一个新终端运行eval "$(curl https://get.x-cmd.com)"后,可以正常使用, 但是在source ~/.zshrc 或者重新打开一个新的终端时,就会报错xxx is not a valid file

**Comment by edwinjhlee** [comment]
仅根据你提供的信息, 我们无法复原. 

我刚又在 alpine zsh 上试装了一次最新版, 无意外是无法复原的.

---

请按照 issue 模板 提供更详细的信息辅助 ~ 系统, zsh 版本, 截图, 等任何你觉得跟解决这个问题相关的资讯.

另外, 存在可能与你的 zshrc 的其它插件冲突. 例如 已知 x-cmd 就也 zinit 默认自带的 x 插件冲突. 所以最好提供 zshrc 的脱敏文本.


---

谢谢

**Comment by skinhc** [comment]
> 另外, 存在可能与你的 zshrc 的其它插件冲突. 例如 已知 x-cmd 就也 zinit 默认自带的 x 插件冲突. 所以最好提供 zshrc 的脱敏文本.

我解决了 需要将zsh自带的extract 插件删除

**Comment by skinhc** [comment]
我解决了 需要将zsh自带的extract 插件删除
