### ISSUE TITLE
是否有计划支持第三方转发openai api key？| 补上 OpenAI 模块中的 endpoint 配置项

### ISSUE THREAD

**Issue by Arteiimis** [x-cmd/x-cmd#15]
首先感谢作者提供如此高质量的终端工具！对于ai的支持也很到位，希望能够支持第三方key，使用成本更低一些

**Comment by edwinjhlee** [comment]
这个很有意思 ～ 

第三方 key 具体是什么 ？ 能不能给我一个案例 ？

如果实现简单的话，我们可以在下周版本加上。

谢谢 支持 ～

**Comment by edwinjhlee** [comment]
如果有隐私问题，不方便公开讨论，你可以加我们 微信订阅号 oh my x，然后 后台给我发信息。

**Comment by Arteiimis** [comment]
> 如果有隐私问题，不方便公开讨论，你可以加我们 微信订阅号 oh my x，然后 后台给我发信息。

倒没有隐私问题，只是我一直在用的一个转发api，避免广告嫌疑，后台私信你吧

**Comment by edwinjhlee** [comment]
> > 如果有隐私问题，不方便公开讨论，你可以加我们 微信订阅号 oh my x，然后 后台给我发信息。
> 
> 倒没有隐私问题，只是我一直在用的一个转发api，避免广告嫌疑，后台私信你吧

其实你可以用 gemini，免费版足够 命令行使用。

**Comment by edwinjhlee** [comment]
我们加一个配置项，应该就配置 endpoint 好了 。

有意思的是，其实 其它厂家的 我们 都做了 endpoint，但 openai 模块可能做得太早了，结果反过来忘了做 endpoint 配置项。

估计下周三我们会发布吧。在此之前可以改代码中的地址 -- 应该很简单。

https://github.com/x-cmd/x-cmd/blob/v0.3.7/mod/openai/lib/request#L42

**Comment by Zhengqbbb** [comment]
```sh
cat "$___X_CMD_ROOT/v/.694dca40/mod/openai/lib/request"
```

![CleanShot 2024-05-17 at 17 57 08@2x](https://github.com/x-cmd/x-cmd/assets/40693636/ee809ccf-14b2-4040-bad5-f2a13a57eb44)

**Comment by edwinjhlee** [comment]
@Arteiimis  已经写好并测试了，下周发版时应该就能通过 配置来修改 endpoint 了。

非常有价值的 issue。谢谢。

**Comment by Arteiimis** [comment]
> @Arteiimis 已经写好并测试了，下周发版时应该就能通过 配置来修改 endpoint 了。
> 
> 非常有价值的 issue。谢谢。

好的，十分感谢！
