### ISSUE TITLE
["DISCUSSION"] difference with https://github.com/pkgXdev/pkgx ?

### ISSUE THREAD

**Issue by happy15** [x-cmd/x-cmd#18]
Hey, cool project 👏

Just wonder: what's the difference between x-cmd and https://github.com/pkgXdev/pkgx ?

Thanks.

**Comment by edwinjhlee** [comment]
That's a very good question.

pkg management is not x-cmd's target. x-cmd aims to modernize the whole traditional posix commands ecosystem. Providing a portable tool management is just one step for this goal.


1. x-cmd is posix-shell library. It is lightweight (1MB), low overheads(1-3ms), implemented by shell, which exists in almost every modern operating system. Pkgx is implememted in nodejs/typescript.
2. x-cmd is embeded into the shell enviornment as a library of functions. So it can extend your shell environment easily.
3. x-cmd can integrate pkgx as one of its module, just like we integrate [asdf module](https://cn.x-cmd.com/mod/asdf). But besides that, x-cmd have a lot of modules, which can extend the original shell command with the lowest possible overheads.


---

Interestingly, at the very first begining, I wrote something simliar of x-cmd in typescript. Then I rewrite the project in go, c, bash, finally I in posix shell. Just for two reasons, which now become x-cmd's the main tech advantages:

1. latenycy/overhead -- the startup speed and startup overhead of commands being wrapped. The latency is the first reason that I give up typescript experiment in 2019. Even I noticed deno and wasm might address these issues to some extent in 2019.
2. lightweight -- our original size is 100KB, unfortunately it is now 1MB. The nodejs/typescript runtime itself exceeds 15MB.


The extensibility is now one of the main advantage of x-cmd, which I didn't noticed backed at 2021. Shell is the best wrapper for binary. Our modules are not aiming to replace the original commands, but to extend them. The original commands are still there, and you can use them as usual. But with our modules, you can do more things with the original commands.

---

For example, if you are go/rust user, you want to provide a better ls. You will write a new project, like [exa](https://x-cmd.com/mod/exa)/[eza](https://x-cmd.com/mod/eza). In x-cmd's way, we will just write a thin wrapper ( module ) for system ls command, parsing the output, enhance the interactivity.



The wrapper is small ( about serveral kb ), low overhead, transparent ( it is not a compiled binary, you can just see what we do ). The underlying ls command must be fast and reliable, and it is already optimized for years. We utilize its advantage, just make it more user-friendly and powerful.

**Comment by happy15** [comment]
Thanks for the comprehensive explanation.

I want to see how the ollama wrapper is implemented, where can I find the wrapper code?

**Comment by edwinjhlee** [comment]
> Thanks for the comprehensive explanation.
> 
> I want to see how the ollama wrapper is implemented, where can I find the wrapper code?

https://github.com/x-cmd/x-cmd/blob/v0.3.9/mod/ollama/latest
