### ISSUE TITLE
["Typo"] Miniconad python --> Miniconda python

### ISSUE THREAD

**Issue by binbinah** [x-cmd/x-cmd#25]
**Describe the Typo**

I recently came across a spelling mistake in the documentation . Unfortunately, I couldn't locate the specific repository for the documentation, so I'm reaching out here to bring this to your attention.

the link is: https://cn.x-cmd.com/pkg/python#x-cmd-%E4%B8%8E-python

**Screenshots**

<img width="780" alt="image" src="https://github.com/x-cmd/x-cmd/assets/5344741/c2356aa1-ffac-4912-aad9-1866ba5dcc64">

**Comment by edwinjhlee** [comment]
I thank you.

**Comment by Zhengqbbb** [comment]
LFG. fixed ~
Thx point it out 🤗
