### ISSUE TITLE
["BUG"] Asks for tcsh integration when running upgrade | [mod=tcsh] [v0.3.15]

### ISSUE THREAD

**Issue by iandol** [x-cmd/x-cmd#26]
**Describe the bug**

When I use `x upgrade` after the upgrade completes it asks me to "configure" `tcsh`. I've never used `tcsh` before on this machine deliberately. See the output here:

```
ε ➪ x upgrade
- I|x: Upgrading x-cmd version => latest
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3902    0  3902    0     0  15604      0 --:--:-- --:--:-- --:--:-- 15608
[2024-06-24/18:53:43] ------------------ 2024-06-24_18:53:43
[2024-06-24/18:53:43] Download script archieve from https://oss.resource.x-cmd.com/x-cmd/release/dist/latest.tgz
[2024-06-24/18:53:44] Download SUCCESS: /Users/ian/.x-cmd.root/v/latest.36798.2024-06-24_18:53:43/download_tmp.tgz ( size: 1384.12 KB )
[2024-06-24/18:53:44] Deflation SUCCESS: /Users/ian/.x-cmd.root/v/latest.36798.2024-06-24_18:53:43/download_tmp.tgz
- I|x: Running x boot init
- W|x: Current version is already latest
- I|x: Already installed in /Users/ian/.shinit
- I|x: Already installed in /Users/ian/.bashrc
- I|x: Already installed in /Users/ian/.bash_profile
- I|x: Already installed in /Users/ian/.zshrc
- I|x: Already installed in /Users/ian/.kshrc
- I|x: You can run the following command to SETUP x-cmd in tcsh.
  more:
    cmd: x tcsh --setup
- I|x: You can run the following command to SETUP x-cmd in elvish.
  more:
    cmd: x elv --setup
- I|x: Updating the resource package => x pkg update
- I|pkg: Update PKG resource
- I|pkg: Download v0.1.1.tar.gz form https://oss.resource.x-cmd.com/x-cmd/pkg/dist/v0.1.1.tar.gz
- I|pkg: Download v0.1.1_hash.txt from https://oss.resource.x-cmd.com/x-cmd/pkg/dist/v0.1.1_hash.txt
- I|pkg: Update the v0.1.1.tar.gz success
- I|advise: Update x-cmd advise
- I|advise: Download all.tar.xz from https://oss.resource.x-cmd.com/releases/advise/v0.0.3/all.tar.xz
- I|x: Initialization SUCCESS
[2024-06-24/18:54:08] x-cmd detected in current shell env. Opening a new shell to avoid collision.

⌃a,e: ⇄ | ⌃w,k,u: 🔪 | ⌃r,s: 🔍 | d, cd - & cd #n: 🚀 | 💡 curl cheat.sh/?

- I|advise: Generate x advise jso - /Users/ian/.x-cmd.root/local/data/advise/cache/x/.dc51f097.jso

Seneca » ~ 
ζ ➪ 
```

My system shell is zsh (macOS system) but my configured shell in my terminal is elvish. 

1. It shouldn't ask to setup `tcsh`.
2. It is a bit annoying that upgrade offers to run `--setup`, it seems upgrading doesn't need to keep asking for setup, setup is something that is done only **once**, upgrade is something that is done **regularly**...
3. After finished, it tells me it needs to open a new shell, but it opens zsh, whereas `x upgrade` was run from Elvish and I'd like it to open a new `elvish` session not revert to `zsh`.

**System (please complete the following information):**
 - Version: sum: dc51f097964ddb277a2296483972a070a85e129c958518c6e11622764c3eecde952a49311b0252cb11cadc7267b715dcf5fe097ab3748970b9d5b5cfcc2319f8
 - Shell: Elvish
 - OS: Darwin
 - Arch: arm64

**Screenshots**

**To Reproduce**
1. run `x upgrade` in Elvish.

**Expected behavior**
Not ask to setup `tcsh`. Ideally not try to setup my shell at all.

**Additional context**

**Comment by edwinjhlee** [comment]
It is quite annoying. I will address this issue in the next version.

**Comment by edwinjhlee** [comment]
Maybe next version will act like this: 

> We just provide suggestions. No auto-setup. 
> I think most of the non-posix shell users are experienced, they could take care of it.

<img width="596" alt="image" src="https://github.com/x-cmd/x-cmd/assets/4426319/71b03f18-2925-4daf-b7ba-aafa02dbaac6">

**Comment by iandol** [comment]
Ideally, the suggestions should trigger if the setup has changed. For example, if `x.elv` has a new version then suggest the user to `--setup`, otherwise no need, but this seems quite complex to implement?

**Comment by edwinjhlee** [comment]
> Ideally, the suggestions should trigger if the setup has changed. For example, if `x.elv` has a new version then suggest the user to `--setup`, otherwise no need, but this seems quite complex to implement?

I did consider adding version to x.elv ... 
It not just complex to implement, but also introducing multiple versions of x.elv to the end user.


Currently, I intend to make the whole implementation as naive/simple/transparent as possible. So they can understand what we do to their elv.rc and manage to make it works in the corner cases base upon their understanding.

**Comment by edwinjhlee** [comment]
> Ideally, the suggestions should trigger if the setup has changed. For example, if `x.elv` has a new version then suggest the user to `--setup`, otherwise no need, but this seems quite complex to implement?

I can check whether the setup is necessary by comparing the files. 
Before introducing this feature, I will have to find out the simplest and accurate way that can works on all environments... 
Given the environment may vary, we might introduce potentials bugs like lacking md5sum in the target environment.

And The boot process is vital step to the installation.

So I must be very cautious ...

Your advise is valuable. I appreciate it a lot.

**Comment by edwinjhlee** [comment]
The version v0.3.13 release with improvements in boot.
In the next version v0.3.14, we will check whether setup is required before prompting in logs.

**Comment by edwinjhlee** [comment]
I forgot optimizing it in v0.3.14 ~
I will leave this in v0.3.15 ~

**Comment by edwinjhlee** [comment]
This issue has been already resolved. Please check it out and confirm.

**Comment by iandol** [comment]
yup, while it still asks me to setup tcsh the important problem of switching to zsh from elvish is fixed, thanks!

**Comment by edwinjhlee** [comment]
> yup, while it still asks me to setup tcsh the important problem of switching to zsh from elvish is fixed, thanks!

that‘s the situation lack of consideration ～ tcsh is installed in mac by default but is seldom
 used. And the prompt
 is kind of annoying ~
 
I don’t have the solution. 
I will keep this issue open, maybe oneday i will
have a better strategy.

**Comment by edwinjhlee** [comment]
I don't think we can have a better strategy in the future.

I will continue to support tcsh out of respect for its legacy.  

Instead of requiring a tcsh upgrade, we provide five lines of setup instructions for tcsh. I assue it wouldn't bring up too much trouble for the non-tcsh users ~

Thanks for your suggestions.
