### ISSUE TITLE
["BUG"] x env use jq not working | [mod=fish,elv,onsh,tcsh,nu] [v0.3.14]

### ISSUE THREAD

**Issue by QianChenglong** [x-cmd/x-cmd#27]
**Describe the bug**

PATH seems miss with install target dir

global != local

<img width="1089" alt="image" src="https://github.com/x-cmd/x-cmd/assets/1881126/1288ace6-6b12-40e2-a5d8-4d0a0a88eea3">
<img width="931" alt="image" src="https://github.com/x-cmd/x-cmd/assets/1881126/13a4b0ef-02f1-4143-8e34-0f72f950c2c7">

**System (please complete the following information):**
OS: macOS 14.5 23F79 x86_64
Host: MacBookPro18,1
Kernel: 23.5.0
Uptime: 14 days, 2 hours, 45 mins
Packages: 135 (brew)
Shell: fish 3.7.1
Resolution: 1728x1117@2x
DE: Aqua
WM: Spectacle
Terminal: alacritty
CPU: Apple M1 Pro
GPU: Apple M1 Pro
Memory: 6158MiB / 32768MiB

**Screenshots**

**To Reproduce**
1. Start up service: '...'
2. Type command: '...'

**Expected behavior**

**Additional context**

**Comment by edwinjhlee** [comment]
Hi ~

```
x env use jq
jq
```

or just 

```
x jq # no installation
```

How about trying again ?

**Comment by QianChenglong** [comment]
I using by function now;
```fish
function x --description 'alias x x'
 command bash -i -c "x $argv"
end
```

**Comment by edwinjhlee** [comment]
It should works like this in fish normally.

<img width="1508" alt="aaa" src="https://github.com/x-cmd/x-cmd/assets/4426319/63f758e8-420f-45fe-83ba-46df8644dd19">

Have you used 'x fish --setup' and setup the fish rcfile ?

**Comment by QianChenglong** [comment]
@edwinjhlee --setup should remove comment when disabled.
<img width="864" alt="image" src="https://github.com/x-cmd/x-cmd/assets/1881126/7e20bfa9-ae5b-4c54-933c-4b98b171da57">

**Comment by QianChenglong** [comment]
<img width="1190" alt="image" src="https://github.com/x-cmd/x-cmd/assets/1881126/126cc420-dfda-47a1-bf6f-5f892fb6c6d7">
same problem

**Comment by edwinjhlee** [comment]
I am very very sorry that I misunderstand your previous comments.

You actually located the bug. We use the wrong path `.../global/` instead of `.../local/...` .  And we made this mistake in nushell/elv/tcsh/fish/... 

Because we never use fish/nushell/elv as a default shell. The `.../local/...` PATH is always exported to the fish/nushell/elv . 


<img width="655" alt="image" src="https://github.com/x-cmd/x-cmd/assets/4426319/8e5a87a6-1132-4182-9109-3c14779c7580">


To be honest, we don't use fish shell as a routine shell. We are very lucky to have you to help us find out more x-cmd's bugs in fish shell.

Thank you.

**Comment by edwinjhlee** [comment]
I will fix it and release a new version in three days ... Thank you ~~~

**Comment by QianChenglong** [comment]
OK, thank you very much for developing this tool and framework, which provides very good ideas and value. I mainly use fish in my daily life, and we can communicate more later.

**Comment by edwinjhlee** [comment]
> OK, thank you very much for developing this tool and framework, which provides very good ideas and value. I mainly use fish in my daily life, and we can communicate more later.


I'm excited to invite you to participate in the insider preview of x7! This new release will allow you to receive daily updates for x-cmd.
    
Please be aware that x7 is a preview release and may contain bugs or unfinished features. I'm currently preparing documentation outlining potential risks and known issues. 
    
Would you be interested in joining the x7 insider preview and receiving daily x-cmd updates?

**Comment by QianChenglong** [comment]
OK, I'm willing to try and give feedback

**Comment by edwinjhlee** [comment]
> OK, I'm willing to try and give feedback

https://x-cmd.com/start/x7

**Comment by QianChenglong** [comment]
Yes，it's ok in x7.
