### ISSUE TITLE
[FEATURE] complete in fish

### ISSUE THREAD

**Issue by QianChenglong** [x-cmd/x-cmd#29]
**Describe the feature**

subcommand and option complete in fish

**Is is urgent**
Could you elaborate on the urgency of this request?

We're a small team and may not be able to respond immediately. 
But we value x-cmd and our users greatly, and always do our best.

**Additional context**

**Comment by edwinjhlee** [comment]
We are working to apply all of our completions to all non-posix shells ~ It take times. But we are heading towards to it.

Thanks for your suggestions ~~~

**Comment by edwinjhlee** [comment]
Now x-cmd support completion for fish, elvish, nushell, etc ~

Please reopen this issue if the problem persists.

Thanks for your support ~

**Comment by QianChenglong** [comment]
> Now x-cmd support completion for fish, elvish, nushell, etc ~
> 
> Please reopen this issue if the problem persists.
> 
> Thanks for your support ~

Thank you very much for supporting the completion of fish. How can I open it?

**Comment by edwinjhlee** [comment]
> > Now x-cmd support completion for fish, elvish, nushell, etc ~
> > Please reopen this issue if the problem persists.
> > Thanks for your support ~
> 
> Thank you very much for supporting the completion of fish. How can I open it?


Upgrade x-cmd to latest version: `x upgrade`

Upgrade fish shell setting: `x fish --setup`

Then `x <tab>`

Let us know if there is any other problem. Thank you.

**Comment by QianChenglong** [comment]
> > > Now x-cmd support completion for fish, elvish, nushell, etc ~
> > > Please reopen this issue if the problem persists.
> > > Thanks for your support ~
> > 
> > 
> > Thank you very much for supporting the completion of fish. How can I open it?
> 
> Upgrade x-cmd to latest version: `x upgrade`
> 
> Upgrade fish shell setting: `x fish --setup`
> 
> Then `x <tab>`
> 
> Let us know if there is any other problem. Thank you.

not working
<img width="873" alt="Clipboard_Screenshot_1733026032" src="https://github.com/user-attachments/assets/fd85a24c-d935-4d75-b004-f7577b256750">

<img width="1124" alt="Clipboard_Screenshot_1733026057" src="https://github.com/user-attachments/assets/735fef90-d1ff-4613-b2b6-cbb6c4f6b31f">

not found `bind`
<img width="1728" alt="Clipboard_Screenshot_1733026083" src="https://github.com/user-attachments/assets/7218fb71-f22d-493d-b30a-254977854126">

**Comment by edwinjhlee** [comment]
It is wierd. It seems we don't enable this feature in the public release. We might forget to do it.

Before the line of '# boot up x-cmd', please add:

```bash
export ___X_CMD_ADVISE_ACTIVATION_ON_NON_POSIX_SHELL=1
```

**Comment by QianChenglong** [comment]
> It is wierd. It seems we don't enable this feature in the public release. Our inner release enables all experimental features by default.
> 
> There is a chance that we simply forget to enable it.
> 
> Before the line of `# boot up x-cmd`, please add:
> 
> ```fish
> set -g  ___X_CMD_ADVISE_ACTIVATION_ON_NON_POSIX_SHELL 1
> ```

Thank you very much for your patient guidance, it is now in effect, great enhancement!
