### ISSUE TITLE
ssh远程连接中关于theme的问题

### ISSUE THREAD

**Issue by lunrenyi** [x-cmd/x-cmd#3]
### 问题描述
在`vscode`中用`remote ssh`远程连接`Ubuntu`虚拟机，在终端中运行`x theme`命令打开主题面板，按q或选择主题后回车关闭面板时会导致ssh连接异常
### 环境信息
  - 能稳定复现
  - 虚拟机为本地虚拟机
  -  虚拟机内用的 shell的类型以及版本：[e.g.：/bin/bash:5.0.17(1)-release sion]
  - 虚拟机内用的 awk的类型以及版本：[e.g.：GNU Awk 5.0.1, API: 2.0 (GNU MPFR 4.0.2, GNU MP 6.2.0) 版权所有 © 1989, 1991-2019 自由软件基金会(FSF)。]
### 重现步骤
 1. 启动`Ubuntu`虚拟机，打开ssh服务并安装x-cmd
 2. 在`vscode`中用`remote ssh`远程连接`Ubuntu`虚拟机
 3. 在终端中输入`x theme`命令打开主题面板
 4. 按下q键或选择一个主题后按下回车
 5. 此会不断输出"/home/lxb/.x-cmd.root/v/latest/mod/ui/lib/region: 第 141 行： printf: 写错误: 断开的管道"
 6. 再按下任意键，输出停止，ssh连接异常
 7. 稍等一会后会自动重启终端并进行ssh连接，同时会完成主题更换
### 附加信息
![错误](https://user-images.githubusercontent.com/87307989/228792189-a6f954c9-55b1-4a5b-8a8e-d04501d1641f.jpg)

![错误2](https://user-images.githubusercontent.com/87307989/228793252-4f43ef89-fb01-4db2-bc29-2277ddb900c2.jpg)

**Comment by mnnna** [comment]
错误原因：内部有一个并发进程没有kill掉；**已解决；**

**Comment by qiakai** [comment]
跟进程信号有关，下个版本会修复，感谢反馈！
