### ISSUE TITLE
[PKG] globalping

### ISSUE THREAD

**Issue by jimaek** [x-cmd/x-cmd#33]
**Basic Information**

name: globalping
official website: https://www.jsdelivr.com/globalping/cli
source code website: https://github.com/jsdelivr/globalping-cli

**meta**:

- license: MPL-2.0
- version: 1.3.0
- oneline install:
  - `curl -s https://packagecloud.io/install/repositories/jsdelivr/globalping/script.deb.sh | sudo bash && apt install globalping`
  - `curl -s https://packagecloud.io/install/repositories/jsdelivr/globalping/script.rpm.sh | sudo bash && dnf install globalping`
  - `brew tap jsdelivr/globalping && brew install globalping`
  - `choco install globalping`
  - `winget install globalping`

**Provide a tldr like example to help us understand**

- `globalping ping google.com`
- `globalping ping google.com from Amazon,Germany,USA,Dallas --limit 4 --latency`
- `globalping traceroute 1.1.1.1 from China`

**Does this software function well in Windows, Linux, Mac, for amd64 and arm64**

Yes, its cross platform

**Describe this package you'd like to recommend**

It's a simple to use CLI that allows anyone to run networking tests like ping, traceroute, mtr, dns, http from any location in the world.

**Additional context**
<img width="80%" src="https://user-images.githubusercontent.com/1834071/217010016-9da38f12-906a-47cf-adca-18017588efe5.png">

**Comment by edwinjhlee** [comment]
Thank you. It is very resourceful.

We will add it to our pkg and install system tomorrow. 

---


Globalping is a really cool tool! I'm impressed with its ability to specify the location for ping launches. 
    
I've also been exploring Shodan, which offers a similar service through its API:
https://x-cmd.com/mod/shodan/geo#x-shodan-geo-geoping

However, it seems Globalping provides more granular control over the ping origin, which is a valuable feature. 
    
Thanks for sharing this resource!

**Comment by jimaek** [comment]
Glad that it's a good fit and you like it :)

**Comment by edwinjhlee** [comment]
Now globalping is ready in x-cmd.

First, users should update index:  `x pkg update`

```bash
# use globalping without installation and effect on your system/user/shell
x globalping -h
```

## using globalping only on this shell session

```bash
x env try globalping
globalping [...args]
```

## install globalping on userspace

```bash
x env use globalping
globalping [...args]
```


## explore different methods to install globalping

```bash
x install globalping

```

**Comment by jimaek** [comment]
Awesome, thank you

**Comment by edwinjhlee** [comment]
> Awesome, thank you

Our team writes an article about globalping and published in our blog and weixin ( Social media platform in China ), mainly to the users in China.

We have an English translated version here:

https://www.x-cmd.com/blog/240706

Feel free to read and suggests ~ Thank you.
