### ISSUE TITLE
[FEATURE] don not use PAGER in ai chat | [mod=chat] [v0.3.14]

### ISSUE THREAD

**Issue by QianChenglong** [x-cmd/x-cmd#34]
<img width="1329" alt="image" src="https://github.com/x-cmd/x-cmd/assets/1881126/67d7cace-ef7a-4f27-8b88-3b4d93c9ad4d">

when quit ,can't see content again.

**Comment by edwinjhlee** [comment]
The llm 类 command has cache. 

If you type the same llm like command again, you can see content again.

<img width="728" alt="image" src="https://github.com/x-cmd/x-cmd/assets/4426319/90cebca7-68e1-4507-bc84-fcfb061bc62a">

---

If x-cmd show all content after quit, in some case, the long output will just mess up the screen and user experience.
So in the future, we might consider show part of the content after quit.

---

Also, we will provde a history navigation in the future. So user can retrieve the last result easily.

---

Thanks for your feedback. 
We will pay more attention on the design of it. Introducing PAGER is out of good intention. We would like to improve it, not to remove it.

**Comment by edwinjhlee** [comment]
But if it happens during the ai chat REPL session, that will be a different story. 
We might just endup do as you request, simply not using less PAGER in that scenario.

**Comment by QianChenglong** [comment]
Yes, I use it in a session, so when I need to see the previous information in context, I can't check it, especially when I'm looking for the previous code snippet.

**Comment by edwinjhlee** [comment]
Please confirm if this this issue is resolved.

**Comment by edwinjhlee** [comment]
I close this issue because it is resolved. If any related problem happened, please reopen it or fire a new issue.

Thank you.
