### ISSUE TITLE
["BUG"] The prompt bar of the Chinese input method is not located near the cursor when in x chat | [mod=chat] [v0.4.4]

### ISSUE THREAD

**Issue by QianChenglong** [x-cmd/x-cmd#35]
**Describe the bug**
The prompt bar of the Chinese input method is not located near the cursor

**System (please complete the following information):**
OS: macOS 14.5 23F79 x86_64
Host: MacBookPro18,1
Kernel: 23.5.0
Uptime: 18 days, 20 hours, 39 mins
Packages: 140 (brew)
Shell: fish 3.7.1
Resolution: 1728x1117@2x, 2560x1440@2x
DE: Aqua
WM: Spectacle
Terminal: zellij
CPU: Apple M1 Pro
GPU: Apple M1 Pro
Memory: 6005MiB / 32768MiB

**Screenshots**
![image](https://github.com/x-cmd/x-cmd/assets/1881126/afc9e1f1-e6d0-4b62-898c-46608a8f4e0e)
<img width="1728" alt="image" src="https://github.com/x-cmd/x-cmd/assets/1881126/c400977e-7431-44b6-8004-9e6c4a477535">

**To Reproduce**
1. Start up service: '...'
2. Type command: '...'

**Expected behavior**

**Additional context**

**Comment by edwinjhlee** [comment]
It is annoying.
But it seems it is not the behavior we could control. 

However, maybe I am wrong. I will take a look into it.

**Comment by edwinjhlee** [comment]
I reproduce the problem. 

It happened in the macos system terminal. In vscode terminal, it works fine.

It is the behavior controled by the macos system terminal. The input characters always docking to left edge or right edge of the terminal app.
In vscode terminal, it always follow the cursor.

Let's see whether we could submit an issue to the Apple Terminal development team to investigate and potentially change this behavior.

**Comment by edwinjhlee** [comment]
There might a chance we could do about it.
Apple terminal doesn't works well with 'gum' with '--width 0' parameter.

```
x gum input --prompt=">>> " --placeholder="..."
```

**Comment by QianChenglong** [comment]
Thank you for your work, it is very easy to use. Because the Chinese input method needs to be combined with the previous text to input, the position of the prompt bar affects the input experience a bit. It would be great if you can continue to polish the details.

**Comment by edwinjhlee** [comment]
The issue with `gum input` has been addressed by switching to `fzf`. 

We've implemented `fzf` as a replacement, providing a more robust solution. Please take a look!

**Comment by edwinjhlee** [comment]
@QianChenglong 

This issue has been resolved with the introduction of chat's new fzf-based input. If you encounter any related problems, please reopen this issue or create a new one.
