### ISSUE TITLE
["BUG"] x update and then x version says x pkg update is required?

### ISSUE THREAD

**Issue by iandol** [x-cmd/x-cmd#39]
**Describe the bug**

I just updated to `1ad27c73` and if I run `x upgrade` it does also run an `x pkg update`,

```bash
ε ➪ x upgrade
- I|x: Upgrading x-cmd version => latest
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3902    0  3902    0     0  14170      0 --:--:-- --:--:-- --:--:-- 14189
[2024-07-07/13:55:43] ------------------ 2024-07-07_13:55:43
[2024-07-07/13:55:43] Download script archieve from https://oss.resource.x-cmd.com/x-cmd/release/dist/latest.tgz
[2024-07-07/13:55:43] Download SUCCESS: /Users/ian/.x-cmd.root/v/latest.99194.2024-07-07_13:55:43/download_tmp.tgz ( size: 1419.29 KB )
[2024-07-07/13:55:44] Deflation SUCCESS: /Users/ian/.x-cmd.root/v/latest.99194.2024-07-07_13:55:43/download_tmp.tgz
[2024-07-07/13:55:44] Folder already existed ==> /Users/ian/.x-cmd.root/v/.1ad27c73
- I|x: Running x boot init
- W|x: Current version is already latest
- I|x: Already installed in /Users/ian/.shinit
- I|x: Already installed in /Users/ian/.bashrc
- I|x: Already installed in /Users/ian/.bash_profile
- I|x: Already installed in /Users/ian/.zshrc
- I|x: Tip to setup x-cmd in tcsh
  more:
    cmd:                   x tcsh --setup
    cmd: ~/.x-cmd.root/bin/x tcsh --setup
- I|x: Tip to setup x-cmd in elvish
  more:
    cmd:                   x elv  --setup
    cmd: ~/.x-cmd.root/bin/x elv  --setup
- I|x: Updating the resource package indexes ...
  more:
    cmd: x pkg update
    tips: If it fails, or is interrupted, you can run it manually later.
- I|pkg: Update PKG resource
- I|pkg: Download v0.1.1.tar.gz form https://oss.resource.x-cmd.com/x-cmd/pkg/dist/v0.1.1.tar.gz
- I|pkg: Download v0.1.1_hash.txt from https://oss.resource.x-cmd.com/x-cmd/pkg/dist/v0.1.1_hash.txt
- I|pkg: Update the v0.1.1.tar.gz success
- I|advise: Update x-cmd advise
- I|advise: Download all.tar.xz from https://oss.resource.x-cmd.com/releases/advise/v0.0.3/all.tar.xz
- I|x: Initialization SUCCESS
[2024-07-07/13:55:45] x-cmd detected in current shell env. Opening a new shell to avoid collision.
```

BUT when running `x version` in the new shell, I see this warning:

```bash
zsh ❯ x version
- I|x: The version information file may be outdated, please try updating the PKG resource package.
  code: x pkg update
.1ad27c73
sum: 1ad27c731c6c6bd873e600b72ed5077e6a22cad1eb65d9a23d94a9b5d3922982696f4a5ad36d2487e8479b6b3c12885e3ae2bdafc8f3093ea3dd6a22b33b399d
```

If I run `x pkg update` a second time and then `x version` I **still see this error**.

## A second problem:

After `x upgrade` I get this: 

> x-cmd detected in current shell env. Opening a new shell to avoid collision

That is fine, but I ran from `elvish` but `x` then runs `zsh`. My system shell is `zsh` as it is safer to run the system shell as default, but my terminal kitty runs `elvish` as the interactive shell. Can you check which shell `x upgrade` was run from then launch that shell? I just launch a new tab in kitty and close that one so it isn't a major issue.

**System (please complete the following information):**
 - Version: 1ad27c73
 - Shell: Elvish
 - OS: Darwin
 - Arch: arm64

**Comment by iandol** [comment]
I tried to use `zsh` to run `x upgrade` and then run `x elv --setup` but `x version` still showing the same value:

**Comment by edwinjhlee** [comment]
## Problem 1: Message Clarity
    
The current message in 'x version' about potentially outdated changelog information is causing confusion. We try to tell the users that the changelog is separate from the release tarball and can be updated independently. So the changelog/version info may be different from website.
    
Proposed Solution:
- Lower the message level to "debug".
    

## Problem 2: Non-POSIX Shell Integration

I think we will stop openning a new shell when x-cmd is invoked by the non-posix shell.

**Comment by iandol** [comment]
So 1ad27c73 is the hash of the release tarball, which itself has no version (is it closer to 0.3.13 or 0.3.14?). Having versioned and unversioned releases is a bit confusing.

**Comment by edwinjhlee** [comment]
After the review of code and careful consideration, I know what is going on about the problem 1.

Our current x-cmd-pkg latest release is older than our x-cmd core release ... Because we have added any new pkg since we created v0.3.14 tarball ~

x-cmd-pkg is design to be always "newer" than the x-cmd version. Because the version information is stored in the x-cmd-pkg. When there is a new x-cmd release, there is always an update on x-cmd-pkg.

We just need to update the x-cmd-pkg release and ensure the x-cmd-pkg release is "newer" to the x-cmd release in the future.

**Comment by edwinjhlee** [comment]
> So 1ad27c73 is the hash of the release tarball, which itself has no version (is it closer to 0.3.13 or 0.3.14?). Having versioned and unversioned releases is a bit confusing.

I confirm this is v0.3.14

**Comment by edwinjhlee** [comment]
If you 'x pkg update', or just 'x upgrade', you can see the version name as below.

<img width="1084" alt="image" src="https://github.com/x-cmd/x-cmd/assets/4426319/c1cae824-dce8-4181-b9c0-76c64c555c2b">

We just release a new version - v0.3.15 ~
https://www.x-cmd.com/v/0.3.15/

**Comment by iandol** [comment]
I am on the x7 branch so i can't confirm, but if it is fixed I'll close this...
