### ISSUE TITLE
每次登录都有这样的提示 | BUG: advise模块中的cp未规避alias | 已在v0.1.3修复

### ISSUE THREAD

**Issue by onesmail** [x-cmd/x-cmd#4]
每次登录成功后都有下面的提示，是需要设置什么吗？
![image](https://github.com/x-cmd/x-cmd/assets/9582449/ec3959a3-0924-4ef3-861f-dd2ccd56deb7)

**Comment by edwinjhlee** [comment]
一般而言，cp会默认overwrite。当前应该cp被alias （加了默认参数，估计是oh-my-zsh的问题。）
你可以试一试`alias cp`，看输出 ～

我们大部分模块应该都会做了规避这种alias cp的问题，但现在看来还是有漏网之鱼 ～ 
感谢你的反馈，我们会看看advise模块究竟哪里 ～

我们会在最近两天再发一个内测版，届时会解决这个问题 ～
