### ISSUE TITLE
[PKG] carapace-bin

### ISSUE THREAD

**Issue by iandol** [x-cmd/x-cmd#40]
**Basic Information**

name: carapace-bin
official website: https://carapace-sh.github.io/carapace-bin/
source code website: https://github.com/carapace-sh/carapace-bin

https://carapace-sh.github.io/carapace-bin/install.html

**meta**:

- license: MIT
- version: 1.0.4
- oneline install:
  - curl from https://github.com/carapace-sh/carapace-bin/releases and unzip binary
  - `brew tap rsteube/homebrew-tap && brew install rsteube/tap/carapace`
  - `scoop bucket add extras; scoop install extras/carapace-bin`
  - `nix-shell -p carapace`

**Provide a tldr like example to help us understand**

- `eval (carapace _carapace|slurp); git sh[tab]`

**Does this software function well in Windows, Linux, Mac, for amd64 and arm64**

Yes

**Describe this package you'd like to recommend**

Carapace is a multi-shell, multi-OS terminal completion system. It provides detailed completions for >500 packages and you can bridge zsh and bash completions for non-posix shells, and build custom completions using simple-to-understand YAML configs.

**Comment by lunrenyi** [comment]
@iandol Thanks for sharing this resource!
carapace-bin is a very useful tool. We will add carapace-bin to our x-cmd/pkg and x-cmd/install tomorrow.

**Comment by lunrenyi** [comment]
@iandol
hi,We have added carapace-bin to x-cmd/pkg and x-cmd/install.

You can install carapace-bin using the following command:
```sh
x pkg update
x env use carapace-bin
```

**Comment by iandol** [comment]
Great, confirmed added!
