### ISSUE TITLE
[FEATURE]  can choose to turn off alias during installation

### ISSUE THREAD

**Issue by QianChenglong** [x-cmd/x-cmd#41]
Otherwise, it may conflict with my own definition and destroy usage habits.

![image](https://github.com/x-cmd/x-cmd/assets/1881126/72de9581-7ce3-4602-a787-2cccf8f171cb)

**Comment by edwinjhlee** [comment]
OK ~ I will add disable feature in v0.4.0 on Thursday ~ Because tonight we are going to release v0.3.15 ~

**Comment by edwinjhlee** [comment]
Since you are going to try x7 release. I will add disable feature tomorrow. You can try and feeback in minutes ~

https://github.com/x-cmd/x-cmd/issues/27#issuecomment-2214094648

**Comment by edwinjhlee** [comment]
```
x boot alias disable c
```

You can disable [ c | xx | xw | xd | xg | xp | co | coco | chat | writer ]

**Comment by edwinjhlee** [comment]
> ```
> x boot alias disable c
> ```
> 
> You can disable [ c | xx | xw | xd | xg | xp | co | coco | chat | writer ]

```
eval "$(curl https://get.x-cmd.com/x7)"
```

Please don't use x7 in a production environment ~
About the risk: https://www.x-cmd.com/start/x7

**Comment by QianChenglong** [comment]
seems not working
<img width="899" alt="image" src="https://github.com/x-cmd/x-cmd/assets/1881126/78400056-75eb-4f2b-8287-ddb89fd458f6">
<img width="731" alt="image" src="https://github.com/x-cmd/x-cmd/assets/1881126/45ba8cea-2a92-4645-9fe5-107655096007">

**Comment by edwinjhlee** [comment]
That's wiered. I will let my collegue to double check and follow.

**Comment by qiakai** [comment]
> seems not working 似乎不起作用 

Sorry, the previous judgment about disabling alias c was wrong. It has now been fixed. You can update to version x7. 
Try again `x fish --setup`

**Comment by QianChenglong** [comment]
fixed
<img width="615" alt="image" src="https://github.com/x-cmd/x-cmd/assets/1881126/f838f2d0-a506-4556-bf0f-e44e3057f7e5">

**Comment by QianChenglong** [comment]
> > seems not working 似乎不起作用
> 
> Sorry, the previous judgment about disabling alias c was wrong. It has now been fixed. You can update to version x7. Try again `x fish --setup`

Hope to see the corresponding commit for each fix.

**Comment by qiakai** [comment]
> Hope to see the corresponding commit for each fix.

https://github.com/x-cmd/x7/commit/00202c1163d8f9b1ef4ebe39004fdabb3b8d032e#diff-3460fa403fef4a76e93f7e4917f897e5b96c8f3676b213638e27002dccb6d4df
