### ISSUE TITLE
["BUG"] `x go --help` error in fish shell

### ISSUE THREAD

**Issue by QianChenglong** [x-cmd/x-cmd#45]
<img width="1044" alt="image" src="https://github.com/x-cmd/x-cmd/assets/1881126/4d132ef3-74e0-4c5e-9172-799df18f5f69">

**Comment by qiakai** [comment]
Some environment variables were not loaded, causing the referenced files to be missing. This issue has been fixed in the current x7 version.

**Comment by QianChenglong** [comment]
fixed
<img width="938" alt="image" src="https://github.com/x-cmd/x-cmd/assets/1881126/844afcbc-e28d-42dc-85da-12d4f78d862c">

**Comment by qiakai** [comment]
https://github.com/x-cmd/x7/commit/5a2c1e9f98564ebf8c50d6fc154f910a340dbcb4

**Comment by QianChenglong** [comment]
<img width="1726" alt="image" src="https://github.com/x-cmd/x-cmd/assets/1881126/d8aad38f-ebca-4867-b97c-684945d8d3f6">

**Comment by qiakai** [comment]
Oh, github x7 is still a private repository, you can see it on codeberg.
https://codeberg.org/x-cmd/x7/commit/5a2c1e9f98564ebf8c50d6fc154f910a340dbcb4
