### ISSUE TITLE
[FEATURE] Better injection of X into .zshrc / rc.elv etc.

### ISSUE THREAD

**Issue by iandol** [x-cmd/x-cmd#47]
**Describe the feature**

When you install `x`, it injects itself s the last line of the shell initialisation files. This is a problem because it means that the x path is not available for any previous setup. For example, I use starship and other tools. If I install them with `x env` and in my `.zshrc`:

```
eval "$(starship init zsh)"
```

...the command will fail as it comes before the `x` init. The solution is for the user to manually move `[ ! -f "$HOME/.x-cmd.root/X" ] || . "$HOME/.x-cmd.root/X"` earlier in `.zshrc`, but perhaps this needs some documentation or a mention? Ideally `x` would inject itself earlier up the init file, but there may be other issues with that? 

Also it seems `x` does not check if the user moved the file for elvish. If I move `use os; if (os:is-regular $E:HOME/.config/elvish/lib/x.elv) { use x; x:init; }` further up rc.elv so the path is visible to other tools, every time I `x elv --setup` I get `use os; if (os:is-regular $E:HOME/.config/elvish/lib/x.elv) { use x; x:init; }` injected as the last line, now I have two repeat lines (I don't think it causes a problem however). Tools like mamba or conda use file comments to find the part of the init file to edit so they know if they already injected themselves or not:

```
# >>> mamba initialize >>>
...inject here
# <<< mamba initialize <<<
```

**Is is urgent**
No

**Comment by edwinjhlee** [comment]
In the normal circumstances, if user using 'x env' to install a pkg, the x rc injection is already done.

So the pkg's activation will be after the '[ ! -f "$HOME/.x-cmd.root/X" ] || . "$HOME/.x-cmd.root/X"' ...


However, sometimes it is not that ideal. I think I can only trust our users's wisdom and leave it to them.
That's also one of the reasons that I only inject one line to rc file, and try to make x-cmd boot more comprehensive.

Just as you suggested, I will add more documentation.


---

About the lines injected, it will check whether the line is already existed. 
However, if the old line is slightly differently from the new line, we will inject the new line.

We can delete the old line by find the '# x-cmd' tag, but what if we are wrong ? So the best thing I could do is to give a warning to our users during 'x elv --setup' and leave it to our users.

When it comes to deleting things, it's better to do nothing than risk making a mistake.

**Comment by edwinjhlee** [comment]
I am afraid there is nothing we could do about it. But adding more documentations.

But we can leave this issue open for a while. Maybe we can come up with something in the future.

**Comment by edwinjhlee** [comment]
x-cmd can manage starship just like we manage pixi.

The activation of starship is during x-cmd booting process.

In our pkg system, we can inject the rc startup managment. However, it now just works on posix shell environment.

That requires some modification on pkg system and its boot design in the whole picture. Let me think twice.

**Comment by iandol** [comment]
Right, I think it is the users job to deal with setup in their own startup files. BUT I would prefer that `x` does not inject itself at the end of `.zshrc` or `rc.elv` at all or at least asks the user if it can inject itself...

**Comment by edwinjhlee** [comment]
> Right, I think it is the users job to deal with setup in their own startup files. BUT I would prefer that `x` does not inject itself at the end of `.zshrc` or `rc.elv` at all or at least asks the user if it can inject itself...

That's difficult decision.
If we don't inject to zshrc, people install the script in bash. Then there will be issues about why x-cmd cannot work in zsh while it can work in bash, or feature requesting.

I think x-cmd installation should be friendly to beginners. As for the advanced users, I think they can take care of the possible complexity it introduce. 
All I need to do is to leave enough log and documents, which I am going to improve in the near future.

**Comment by edwinjhlee** [comment]
I am closing this issue. If any related problems mentioned here remain unresolved, please reopen this issue or create a new one.

BTW, we have introduce [starship](https://x-cmd.com/mod/starship) module in the latest release, v0.4.13 ~
