### ISSUE TITLE
[FEATURE] Support up and down search for the input content in ai chat | [mod=chat] [v0.4.4]

### ISSUE THREAD

**Issue by QianChenglong** [x-cmd/x-cmd#51]
I often need to slightly adjust the prompt words. It would be much more convenient if I could quickly get the previous input content and modify it.

<img width="675" alt="image" src="https://github.com/x-cmd/x-cmd/assets/1881126/9e9d9f82-2392-402a-8aba-5d56d5418271">

**Comment by edwinjhlee** [comment]
We cannot implement this feature in the current model. But we will introduce a much better repl model later.

**Comment by edwinjhlee** [comment]
We've implemented `fzf` as line edit with history support. 
Please take a look ~

**Comment by edwinjhlee** [comment]
@QianChenglong 

This issue has been resolved with the introduction of chat's new fzf-based input. If you encounter any related problems, please reopen this issue or create a new one.
