### ISSUE TITLE
[FEATURE] x proxy also sets git proxies

### ISSUE THREAD

**Issue by iandol** [x-cmd/x-cmd#54]
**Describe the feature**

`x proxy` sets the env variables, but git also has a `http[s].proxy` config setting:

```
git config --global http.proxy $E:http_proxy
git config --global https.proxy $E:https_proxy
```

I think `x proxy` should also set the git proxy settings when you run e.g. `x proxy set 127.0.0.1:8888`

To unset:

```
git config --global --unset http.proxy
git config --global --unset https.proxy
```

This is how I do this in my own elvish proxy command:

https://github.com/iandol/dotfiles/blob/master/aliases.elv#L221

**Is is urgent**

no, I think git falls back to http_proxy env variable? But it is better practice to set the official settings when available...

**Additional context**

**Comment by edwinjhlee** [comment]
HTTP_PROXY and HTTPS_PROXY will actually take effects on git command.
But if git is using ssh/git protocol, neither HTTP_PROXY/HTTPS_PROXY won't take effect.

About setting proxy in git, we have a command for Chiense user:

```bash
x git sp set <proxy>:<port>
x git sp status
x git sp unset
```

**Comment by edwinjhlee** [comment]
We won't change git config in 'x proxy'. If we did that, we would also have to add proxy to other softwares in 'x proxy'.

'x proxy' is designed just for one scenario, quicky setting all common proxy environment variables.

**Comment by iandol** [comment]
OK, I'll close this.
