### ISSUE TITLE
["BUG"] Option to not spawn a new shell with x upgrade

### ISSUE THREAD

**Issue by iandol** [x-cmd/x-cmd#57]
**Describe the bug**

We discussed this before, but when I run `x upgrade` from Elvish, a zsh shell session is returned. As I also use `x upgrade` in a script (I run several updates for my shell environment), it is even less desired, as it stops my update script from running. You could change the default behaviour, or maybe better add an option like `x upgrade --nospawn` or something similar.

**System (please complete the following information):**
 - Version: dc722741c1d3fee6019067c
 - Shell: Elvish
 - OS: Darwin
 - Arch: arm64

**Comment by edwinjhlee** [comment]
Oh. I forget to fix this issue. 

We have an environment to label this is calling from non-posix shell. And we will just exit the posix shell after update.

**Comment by edwinjhlee** [comment]
Hi ~ 

I have updated the script in the https://get.x-cmd.com. 
Please confirm if this issue has been resolved.

**Comment by iandol** [comment]
Fixed and working as I hope thanks!
