### ISSUE TITLE
How to contribute to this repo?

### ISSUE THREAD

**Issue by xgqfrms** [x-cmd/x-cmd#6]
Is there some wiki or guideline for the contributor?

**Comment by edwinjhlee** [comment]
Hello. First of all, thank you for your support.

  To ensure overall design and engineering quality, as well as development efficiency, x-cmd adopts a company team development model. However, we are very willing to cooperate with community developers in the future, and we plan to gradually open the development repositories of some modules in the future.

  Currently, if you find any bugs, performance issues, or have better solutions, please feel free to post an issue on GitHub.

  In China, you can also interact with us on Gitee or Gitcode:
  https://gitee.com/x-cmd/x-cmd/issues
  https://gitcode.net/x-cmd/x-cmd/issues

----------

你好。首先，感谢你的支持。

为了保证整体设计和工程质量，以及开发效率，x-cmd 采用公司团队开发模式。
但是我们非常乐意在日后和社区开发者的合作，我们计划在未来陆续开放部分模块的开发仓库。

当前，如果你发现有 bug，或者发现性能问题，或者有更好的解决思路，欢迎在github上发 issue。

在中国，你也可以在 gitee 或者 gitcode 上跟我们互动:
https://gitee.com/x-cmd/x-cmd/issues
https://gitcode.net/x-cmd/x-cmd/issues
