### ISSUE TITLE
[PKG] <name of recipe, like python, tmux>

### ISSUE THREAD

**Issue by 13321880996104311** [x-cmd/x-cmd#60]
**Basic Information**

name: <PKG name>
official website: 
source code website: [e.g. https://github.com/x-cmd/x-cmd]

**meta**:

- license: [e.g. GPLv3, BSD, MIT, etc...]
- version: [e.g. 1.0.0]
- oneline install:
  - [ For example, `apt install ...` ]
  - [ For example, curl ... | sh ]
  - ...

**Provide a tldr like example to help us understand**

- [ basic usage 1 ]
- [ basic usage 2 ]
- ...

**Does this software function well in Windows, Linux, Mac, for amd64 and arm64**

**Describe this package you'd like to recommend**

**Additional context**

**Comment by edwinjhlee** [comment]
Since this issue stays invalid for a couple of days, we are going to close it.
You can reopen or submit a new issue when you are ready.
