### ISSUE TITLE
[FEATURE] x jq r support tab to complete | [mod=jq] [wont-fix]

### ISSUE THREAD

**Issue by QianChenglong** [x-cmd/x-cmd#61]
**Describe the feature**
x jq r support tab to complete

<img width="915" alt="image" src="https://github.com/user-attachments/assets/30c76288-68a5-4b0d-9358-103576f53b52">

**Comment by edwinjhlee** [comment]
The currently displayed options are not the complete options for the current cursor, but rather a list of keys from the results of the closest correct jq filter.

We currently have no way to implement jq filter syntax parsing, so it is difficult to achieve complete in the sense of jq filter syntax.
    
We have attempted to solve this in the implementation of jq command completion, but there is currently no good solution.
