### ISSUE TITLE
["BUG"]___x_cmd_replhook_trapint_init:47: command not found: ___x_cmd_replhook_precmd_add ___x_cmd_replhook_trapint_init:48: command not found: ___x_cmd_replhook_preexec_add | [mod=x-cmd] [v0.4.7]

### ISSUE THREAD

**Issue by 1036831050** [x-cmd/x-cmd#64]
**Describe the bug**

**System (please complete the following information):ubuntu20.04
 - Version:20.04
 - Shell: zsh
 - OS: linux
 - Arch:x86_64

**Screenshots**
![image](https://github.com/user-attachments/assets/4404dec2-5ea6-4418-a119-941c1caa66d7)

**To Reproduce**
安装x-cmd之后新开中断就会出现这个提示

**Comment by edwinjhlee** [comment]
好，我们 马上 看一看能否 复现。

**Comment by qiakai** [comment]
执行以下命令，检测是否当前环境有 precmd 和 preexec
```sh
command -v precmd && which precmd && type precmd
command -v preexec && which preexec && type preexec
```

**Comment by edwinjhlee** [comment]
@1036831050 请帮忙看看 环境中 是否有 `precmd` 和 `preexec` ~

应该是 某个机制 导致我们 无法 定义 repl ～ 我们 现在 怀疑是 环境中 已有 precmd 和 preexec  ～

**Comment by 1036831050** [comment]
> 执行以下命令，检测是否当前环境有 precmd 和 preexec
> 
> ```shell
> command -v precmd && which precmd && type precmd
> command -v preexec && which preexec && type preexec
> ```

![image](https://github.com/user-attachments/assets/a45d9156-4d5c-4e04-8c44-d319fb8a2064)

**Comment by edwinjhlee** [comment]
这件事情，我们 得 好好评估一下。我们 当前设计 碰到这个 precmd 和 preexec，就会先退出 repl hook init。

我们会先做个 判断，在这种场景 x-cmd 自行退出 repl hook 的 初始化- 这可能会对 theme 的使用有一点的影响。
在 v0.4.8 的时候，我们再考虑如何 更好的 共存。

非常感谢 你的协助 ～

---

**Comment by edwinjhlee** [comment]
v0.4.7 已经发布，请确认问题 修复 后 关闭 issue 哈 ～
