### ISSUE TITLE
["BUG"] 安装后无法使用x命令 | zsh-extract defined alias x='extract' | [mod=xrc] [v0.4.7]

### ISSUE THREAD

**Issue by 1036831050** [x-cmd/x-cmd#65]
**Describe the bug**

**System (please complete the following information):安卓上的termux
 - Version: [A sha512, type 'x version' so you can get the version sum]
 - Shell: zsh
 - OS: termux
 - Arch: [e.g. amd64, arm64]

**Screenshots**
![image](https://github.com/user-attachments/assets/079ac3a8-6671-461e-881c-53e1ff1ee5ac)

**To Reproduce**
似乎是zsh的extract插件的问题，通过alias查到了x已有别名,添加了注释也没用，还是需要手动unalias
![image](https://github.com/user-attachments/assets/15872dd1-4d85-4395-8d22-f3d7c0e6c2cf)

**Comment by 1036831050** [comment]
希望增加一个别名冲突提示或者直接帮忙卸载这个extract插件

**Comment by edwinjhlee** [comment]
> 希望增加一个别名冲突提示或者直接帮忙卸载这个extract插件

好的。我们马上  看一下 怎么处理。

**Comment by edwinjhlee** [comment]
啧，我们 还真 没有 在 termux 测过 x-cmd ... Cool ~

**Comment by edwinjhlee** [comment]
其实我们没有 设别名，我们是如此定义的：

```bash
x(){
    ___x_cmd "$@"
}
```

而 zsh-extract 的 alias x='extract' 的优先级 更高，把这个函数 给 覆盖了。

---

1. 经过考虑，我们决定还是自私一点 -- 在 x-cmd 启动的时候 自动 unalias x:
   - 毕竟，你还可以通过 extract 命令来使用该插件
   - 或者，可以 重设 alias ex='extract'
2. 以后我们会释放 x 这个别名出来，让用户自主选择 ___x_cmd 的短名，但估计要到 年尾:
   - 例如，用户可以选择设定 exe 等同于 ___x_cmd
   - 我们在半年前 就有这个打算，让用户可以选择 x 以外的其它别名，我们最近半年的很多代码 都已然从 'x' 改成了 '___x_cmd'，但 x-cmd 已经开发三年了，内部发布的和未发布的模块总共有 400 多个；仍有不少稳定的模块还没有来得及修改；所以现在只能出此下策。

---

# Tranlated text for English user:

---

We actually don't have an alias, we define it like this:

```bash
x(){
    ___x_cmd "$@"
}
```

However, zsh-extract's alias x=extract has a higher priority and overrides this function.

---

1. After careful consideration, we decided to be a little selfish -- automatically unalias x when x-cmd starts:
   - After all, you can still use the plugin through the extract command
   - Or, you can reset the alias ex=extract
2. In the future, we will release the x alias, allowing users to choose the short name for ___x_cmd, but it's estimated to be at the end of the year:
   - For example, users can choose to set exe to be equivalent to ___x_cmd
   - We had this plan six months ago, allowing users to choose aliases other than x. Many of our codes in the past six months have already changed from x to ___x_cmd, but x-cmd has been developed for three years, with over 400 internal and unreleased modules; there are still many stable modules that haven't been modified yet; so we have to resort to this solution for now.

**Comment by edwinjhlee** [comment]
在我们 还没发新版本之前，你可能需要在 x-cmd 加载代码 之前，增加一行：
```
unalias x
```

这样就能 正常加载了。


<img width="835" alt="image" src="https://github.com/user-attachments/assets/85cd8262-b1f8-47b0-973d-d63a0acf2738">

**Comment by edwinjhlee** [comment]
v0.4.7 已经发布，请确认问题 修复 后 关闭 issue 哈 ～

**Comment by edwinjhlee** [comment]
是否 方便 贴一下 ~/.zshrc ? 请注意删除可能的稳私信息。

1. 是否采用了 类似 zinit 的 async 框架来加载 ？
2. 在 ~/.zshrc 中 oh-my-zsh的 加载代码 是否在 x-cmd 之后 ？

**Comment by edwinjhlee** [comment]
我猜很有可能是 用了 zsh async 类似的技术，就是刚打开时追求 prompt 显示的速度，然后再在后台 加载相应的 插件 ～

这种情况下，可能我们在 x-cmd 加载 过程中无法再做什么了。否则 x-cmd 对环境的 侵入性 太强了；会带来更多的问题。

**Comment by 1036831050** [comment]
> 是否 方便 贴一下 ~/.zshrc ? 请注意删除可能的稳私信息。
> 
> 1. 是否采用了 类似 zinit 的 async 框架来加载 ？
> 2. 在 ~/.zshrc 中 oh-my-zsh的 加载代码 是否在 x-cmd 之后 ？
> 
> 
> 
> 

没啥隐私，我直接全贴上吧
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]] {
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
}
########
# Note
# If you find a permission problem with zsh-related directories, then try running `compaudit | xargs chmod g-w,o-w`

########
# Set env
path=(~/.local/bin $path)
typeset -x XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
TMOE_ZSH_DIR="${HOME}/.config/tmoe-zsh"
TMOE_ZSH_GIT_DIR="${TMOE_ZSH_DIR}/git"
TMOE_ZSH_TOOL_DIR="${TMOE_ZSH_GIT_DIR}/tools"
ZINIT_THEME_DIR="${HOME}/.zinit/themes/_local"
########
# Setopt
setopt correct
# setopt autocd

setopt interactive_comments
########
load_omz_lib() {
    for i (theme-and-appearance.zsh git.zsh prompt_info_functions.zsh history.zsh) {
        zinit snippet ${HOME}/.zinit/omz/lib/${i}
    }
    for i (completion.zsh key-bindings.zsh) {
        zinit ice lucid wait="1"
        zinit snippet ${HOME}/.zinit/omz/lib/${i}
    }
}
########
load_zinit_compinit_function() {
    # autoload -Uz compinit ;compinit #载入补全相关function
    zpcompinit
    zpcdreplay
    # compinit -u
    # zinit cdreplay -q
}
########
# LOAD MAIN LIB
source ${HOME}/.zinit/bin/zinit.zsh
load_omz_lib
########
# THEME
zinit light ${ZINIT_THEME_DIR}/ys
# theme-and-appearance的加载顺序要先于主题,请在load_omz_lib之后加载主题。
skip_global_compinit=1
load_zinit_compinit_function
########
ALOXAF_FZF_TAB_EXTRA=true
# 当变量ALOXAF_FZF_TAB_EXTRA的值为01时，仅加载补全项颜 色函数;为02时，加载右侧窗口配置;为true时，启用所有额外 函数;为false时禁用。
source ${TMOE_ZSH_GIT_DIR}/config/aloxaf_fzf_tab_extra_opts.zsh
########
zinit ice lucid wait="1" pick"extract.plugin.zsh" && zinit light _local/extract && zinit ice lucid as"completion" wait="1" && zinit snippet ${HOME}/.zinit/plugins/_local---extract/_extract #解压插件，输x 压缩包名称（例如`x 233.7z`或`x 233.tar.xz`) 即可解压文件。This plugin defines a function called `extract` that extracts the archive file you pass it, and it supports a wide variety of archive filetypes.
########
zinit ice lucid wait="1" pick"z.plugin.zsh" && zinit light _local/z && unsetopt BG_NICE #记录访问目录，输z获取,输`z 目录名称`快速跳转  This plugin defines the [z command](https://github.com/rupa/z) that tracks your most visited directories and allows you to access them with very few keystrokes.
########
zinit ice lucid pick"git.plugin.zsh" wait="1" && zinit light _local/git #The git plugin provides many aliases and a few useful functions. git的一些alias,例如将git clone简化为gcl.
########
[[ -e /usr/lib/command-not-found ]] && zinit ice lucid wait="0" pick"command-not-found.plugin.zsh" && zinit light _local/command-not-found #用于显示未找到的命令来源 于哪个软件包  This plugin uses the command-not-found package for zsh to provide suggested packages to be installed if a command cannot be found.

zinit ice lucid wait="3" pick"colored-man-pages.plugin.zsh" && zinit light _local/colored-man-pages #This plugin adds colors to man pages. man手册彩色输出

zinit ice wait lucid pick"fast-syntax-highlighting.plugin.zsh" atinit"ZINIT[COMPINIT_OPTS]=-C; zicompinit; zicdreplay" && zinit light _local/fast-syntax-highlighting #语法高亮插件，速度比zsh-syntax-highlighting更快。(Short name F-Sy-H). Syntax-highlighting for Zshell – fine granularity, number of features, 40 work hours themes

zinit ice wait lucid pick"zsh-autosuggestions.zsh" atload'_zsh_autosuggest_start' && zinit light _local/zsh-autosuggestions #自动建议插件 It suggests commands as you type based on history and completions.

zinit ice lucid wait="2" pick"sudo.plugin.zsh" && zinit light _local/sudo #Easily prefix your current or previous commands with `sudo` by pressing <kbd>esc</kbd> twice 按两次ESC键,可以在当前命令前加上sudo前缀

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh # powerlevel10k的prompt
#######
# ALIASES
alias ...=../..
alias ....=../../..
alias .....=../../../..
alias ......=../../../../..
alias 1='cd -'
alias 2='cd -2'
alias 3='cd -3'
alias 4='cd -4'
alias 5='cd -5'
alias 6='cd -6'
alias 7='cd -7'
alias 8='cd -8'
alias 9='cd -9'
alias _='sudo '
alias afind='ack -il'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias gc1='git clone --recursive --depth=1'
alias globurl='noglob urlglobber '
alias grep='grep --color=auto'
alias md='mkdir -p'
alias rd=rmdir
########
if [[ $(command -v exa) ]] {
    DISABLE_LS_COLORS=true
    unset LS_BIN_FILE
    for i (/bin/ls ${PREFIX}/bin/ls /usr/bin/ls /usr/local/bin/ls) {
        [[ ! -x ${i} ]] || {
            local LS_BIN_FILE=${i}
            break
        }
    }
    [[ -n ${LS_BIN_FILE} ]] || local LS_BIN_FILE=$(whereis ls 2>/dev/null | awk '{print $2}')
    alias lls=${LS_BIN_FILE}
    # lls is the original ls. lls为原版ls
    alias ls="exa --color=auto"
    # Exa is a modern version of ls. exa是一款优秀的ls 替代品,拥有更好的文件展示体验,输出结果更快,使用rust编写。
    alias l='exa -lbah --icons'
    alias la='exa -labgh --icons'
    alias ll='exa -lbg --icons'
    alias lsa='exa -lbagR --icons'
    alias lst='exa -lTabgh --icons' # 输入lst,将展示类 似于tree的树状列表。
} else {
    alias ls='ls --color=auto'
    # color should not be always.
    alias lst='tree -pCsh'
    alias l='ls -lah'
    alias la='ls -lAh'
    alias ll='ls -lh'
    alias lsa='ls -lah'
}
[[ ! $(command -v tmoe) ]] || alias t=tmoe
########
set_bat_paper_variable() {
    unset CAT_BIN_FILE i
    for i (/bin/cat ${PREFIX}/bin/cat /usr/bin/cat /usr/local/bin/cat) {
        [[ ! -x ${i} ]] || {
            local CAT_BIN_FILE=${i}
            unset i
            break
        }
    }
    [[ -n ${CAT_BIN_FILE} ]] || local CAT_BIN_FILE=$(whereis cat 2>/dev/null | awk '{print $2}')
    alias lcat=${CAT_BIN_FILE}
    # lcat is the original cat.
    typeset -g BAT_PAGER="less -m -RFQ" # You can type q to quit bat. 输q退出bat的页面视图
}
# bat supports syntax highlighting for a large number of programming and markup languages. bat是cat的替代品， 支持多语言语法高亮。
for i (batcat bat) {
    if [[ $(command -v ${i}) ]] {
        alias cat="${i} -pp"
        set_bat_paper_variable
        break
    }
}
########
zinit ice lucid wait=1 ascompletion && zinit snippet /data/data/com.termux/files/home/.config/tmoe-zsh/git/share/completion/_zshtheme
[[ $(command -v fzf) ]] && zinit ice lucid pick"fzf-tab.zsh" && zinit light _local/fzf-tab  #aloxaf:fzf-tab 是一个能够极大提升 zsh 补全体验的插件。它通过 hook zsh 补全系统的底层函数 compadd 来截获补全列表，从而实现了在补全命令行参数、变量、目录栈和文件时都能使用 fzf 进行选择的功能。Replace zsh's default completion selection menu with fzf!
alias zshcolor='bash /data/data/com.termux/files/home/.config/tmoe-zsh/git/share/colors.sh'
alias zshfont='bash /data/data/com.termux/files/home/.config/tmoe-zsh/git/share/fonts.sh'

if [ -f ~/.aliases ];then
        source ~/.aliases
fi

# 命令执行区域
sshd
termux-wake-lock
neofetch
eval "$(mcfly init zsh)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
zinit ice lucid wait=1 ascompletion && zinit snippet /data/data/com.termux/files/home/.local/share/tmoe-linux/git/share/old-version/share/completion/_tmoe


[ ! -f "$HOME/.x-cmd.root/X" ] || . "$HOME/.x-cmd.root/X" # boot up x-cmd.

**Comment by edwinjhlee** [comment]
对的，我看到 了 zinit，就知道 用了 zsh-async 框架了。

我本身没有 zinit 的经验，我找个时间 看看 能不能 加一行代码 帮你 unalias。

但如果你想 disable extract 这个插件，你只需要 注释这一行：

```
zinit ice lucid wait="1" pick"extract.plugin.zsh" && zinit light _local/extract && zinit ice lucid as"completion" wait="1" && zinit snippet ${HOME}/.zinit/plugins/_local---extract/_extract
```
