### ISSUE TITLE
The output of downloading is not nice.

### ISSUE THREAD

**Issue by MaxforCherubim** [x-cmd/x-cmd#70]
**Describe the bug**

We can see the picture below.
Why the Progress bar is accumalated?

**System (please complete the following information):**
 - Version: 

`x version  `                                                       
.90b81dd5
version: v0.4.7
date: "2024-08-20 00:07:02+0000"
sum: 90b81dd5f173404e5588f1e4dc3e0c922dfa2b387dfa0e128842fa9ba4d4b6ea9c45e07f24c3265bb3998ba5426d2adf6f33bf55c5abd6e588c003d7c0683164

 - Shell: Zsh 
 - OS: macos
 - Arch: arm64

**Screenshots**

![image](https://github.com/user-attachments/assets/9fd6df03-4396-4ff5-85ce-df4135e1bebb)

**To Reproduce**

1. When you need to download the tool.

**Expected behavior**

the Progress bar of downloading is accumalated

**Comment by edwinjhlee** [comment]
I think there might be a font issue with your terminal. You can try adjusting the Terminal's style settings.

**Comment by MaxforCherubim** [comment]
Thanks for sharing your displaying in mac.
I find the difference between us.
Look at this picture.

<img width="955" alt="image" src="https://github.com/user-attachments/assets/3d5469c2-6614-4d6d-9b03-0ff340c0c6ac">

**There are little blanks between words.**
If not your displaying, I am afraid of disabling to find the fault.
First, let me google this problem.
And have you ever faced this problem?

**Comment by MaxforCherubim** [comment]
OK, I figure out this problem.
It is because of the settings of iTerm2, which is displayed in picture.

<img width="932" alt="截屏2024-08-26 19 54 48" src="https://github.com/user-attachments/assets/5684af03-7038-4cf8-b46d-bf563440cb50">

It set the spacing between letters.

**Comment by MaxforCherubim** [comment]
> I think there might be a font issue with your terminal. You can try adjusting the Terminal's style settings.
> 
> We will consider shutdown the curl progressbar during pkg download in the future.
> 
> But you'd better check the font or style settings on your terminal. Because once it's displayed like this here, there might be refresh issues in quite a few places.
> 
> ## This is how it display in my mac.
> <img alt="image" width="843" src="https://private-user-images.githubusercontent.com/4426319/360932269-aac1dfa4-636a-461a-8c44-bcab6773518d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2ODA3ODIsIm5iZiI6MTcyNDY4MDQ4MiwicGF0aCI6Ii80NDI2MzE5LzM2MDkzMjI2OS1hYWMxZGZhNC02MzZhLTQ2MWEtOGM0NC1iY2FiNjc3MzUxOGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjZUMTM1NDQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGQ1NGNlYTdhYmY4ZWI3ZGE2OTQyOWNlYTc4MDYyNGZjODVhNTc0YmJkM2I0ZjA3ZThiNTNlMzE3MWZjOTAxNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4_DawRBiHJCUETCCRQPwrGj1VvZjvMAmdDanI7Ws03s">

Oh!
What's more.
Would you like to tell me why your terminal display the processing with blue barchart?

**Comment by edwinjhlee** [comment]
> > I think there might be a font issue with your terminal. You can try adjusting the Terminal's style settings.
> > We will consider shutdown the curl progressbar during pkg download in the future.
> > But you'd better check the font or style settings on your terminal. Because once it's displayed like this here, there might be refresh issues in quite a few places.
> > ## This is how it display in my mac.
> > <img alt="image" width="843" src="https://private-user-images.githubusercontent.com/4426319/360932269-aac1dfa4-636a-461a-8c44-bcab6773518d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2ODA3ODIsIm5iZiI6MTcyNDY4MDQ4MiwicGF0aCI6Ii80NDI2MzE5LzM2MDkzMjI2OS1hYWMxZGZhNC02MzZhLTQ2MWEtOGM0NC1iY2FiNjc3MzUxOGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjZUMTM1NDQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGQ1NGNlYTdhYmY4ZWI3ZGE2OTQyOWNlYTc4MDYyNGZjODVhNTc0YmJkM2I0ZjA3ZThiNTNlMzE3MWZjOTAxNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4_DawRBiHJCUETCCRQPwrGj1VvZjvMAmdDanI7Ws03s">
> 
> Oh! What's more. Would you like to tell me why your terminal display the processing with blue barchart?

I am using it to hide personal information. It is not generated by x-cmd.
