### ISSUE TITLE
["BUG"] Nu shell integration is broken | [mod=nu] [v0.4.9]

### ISSUE THREAD

**Issue by yarnaid** [x-cmd/x-cmd#73]
**Describe the bug**
I've just installed the latest version of x-cmd and it breaks my nushell config.

**System (please complete the following information):**
 - Version: 0.4.8
 - Shell: nushell
 - OS: macOS
 - Arch: arm64

**Screenshots**

![PixelSnap 2024-08-30 at 12 04 08@2x](https://github.com/user-attachments/assets/5790f340-e1c6-487c-810b-480b79f45450)

**To Reproduce**
1. install nu shell integration
2. start a new session

**Expected behavior**
Nu shell works as before with x-cmd integration.

**Additional context**
Solution: change in .x-cmd.root/local/data/nu/rc.nu on lines 65 and 99 `exit_code` -> `^exit_code`

**Comment by curry798** [comment]
Thank you for your feedback! 
This is due to a significant breaking change introduced in the latest version of nushell. 
We'll fix it in the next release.

**Comment by edwinjhlee** [comment]
Thank you for reporting this bug ~
    
We've identified an issue in our code that was highlighted in the compile time by the new Nushell interpreter. 
    
We have provided a fix for the upcoming v0.4.9 release,
    
In the meantime, the issue has been addressed in our x7 developer release, which will be included in the upcoming v0.4.9 release. You can try x7 release: https://www.x-cmd.com/start/x7 ~

**Please note that using the x7 release may come with potential risks as it is a development version.**

**Comment by edwinjhlee** [comment]
Hi @yarnaid  ~ Please confirm whether this issue is fixed before closing this issue.

**Comment by yarnaid** [comment]
Yes, it works, thank you!
