### ISSUE TITLE
["BUG"] Unset brew mirror not working

### ISSUE THREAD

**Issue by iandol** [x-cmd/x-cmd#74]
**Describe the bug**

I used `x brew mirror set tuna` which works well in China but travelling back to europe it doesn't work well. So I tried `x brew unset`, but `brew update` fails:

```
ε ➪ x brew mirror current 
HOMEBREW_API_DOMAIN=
HOMEBREW_BOTTLE_DOMAIN=
HOMEBREW_BREW_GIT_REMOTE=
HOMEBREW_CORE_GIT_REMOTE=
GIT_DIR=https://github.com/Homebrew/brew
                                                                                                                                 
Seneca » ~ 
ε ➪ brew update
==> Updating Homebrew...
fatal: unable to access 'https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git/': Failed to connect to mirrors.tuna.tsinghua.edu.cn port 443 after 75365 ms: Couldn't connect to server
Error: Fetching /opt/homebrew/Library/Taps/homebrew/homebrew-core failed!
==> Updated Homebrew from dfe28d8944 to 019b0f50fb.
No changes to formulae or casks.
Exception: brew exited with 1
  [tty 2]:1:1-11: brew update
```

The problem is the git repo is still set to tuna:

```
Seneca » …/homebrew-core on  master via 💎 v3.3.3 
ε ➪ git remote -v
origin	https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git (fetch)
origin	https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git (push)
```

**System (please complete the following information):**
 - Version:  df939bc2198b5d667
 - Shell: elvish
 - OS: darwin
 - Arch: arm64

**Expected behavior**
`unset` reverts brew back to the standard repo.

**Comment by iandol** [comment]
This fixes the error (for homebrew core):
```
Seneca » …/homebrew-core on  master via 💎 v3.3.3 
ε ➪ git remote set-url origin https://github.com/Homebrew/homebrew-core.git
```

**Comment by edwinjhlee** [comment]
Thanks. We will take a look at it.

**Comment by lunrenyi** [comment]
- **Reason**: In `x brew unset`, we used the [brew tap](https://docs.brew.sh/Taps#the-brew-tap-command) command to restore the remote URL of the repository, but it didn't actually work.

**Starting from version 4.10.0**, we will use the `git -C "$(brew --repo [repo_name])" remote set-url origin [new_url]` method to restore the remote URL of the repository in order to fix this issue.

**Comment by lunrenyi** [comment]
We discovered a cleaner method of setting download sources using [Homebrew's environment files](https://docs.brew.sh/Manpage#environment), so we'll be adjusting the implementation of `x brew mirror set/unset` in the new version.
