### ISSUE TITLE
[PKG] oma

### ISSUE THREAD

**Issue by eatradish** [x-cmd/x-cmd#77]
**Basic Information**

name: oma
official website: https://github.com/aosc-dev/oma
source code website: https://github.com/aosc-dev/oma

**meta**:

- license: GPLv3
- version: 1.9.3
- oneline install:

```bash
curl -sSf https://repo.aosc.io/get-oma.sh | sh
```

**Provide a tldr like example to help us understand**

- Install a package: `oma install foo`
- TUI interface: `oma tui`
- Search a package: `oma search foo`
...

**Does this software function well in Windows, Linux, Mac, for amd64 and arm64**

Debian (Ubuntu) distro, and `libapt-pkg` >= 6.0

**Describe this package you'd like to recommend**

`oma` is is a package manager frontend for `libapt-pkg` . oma has fridendly interface, Multi-thread download, smart search, undo, and ... more features.

**Comment by edwinjhlee** [comment]
Thank you.

We will initially include it in  [`x install`](https://x-cmd.com/install). Once the project stabilizes and updates become less common, we'll add it to into [pkg](https://x-cmd.com/pkg).

**Comment by eatradish** [comment]
> https://www.x-cmd.com/install/oma
> 
> @eatradish
> 
> Considering:
> 
>     1. x-cmd's `pkg` functionality primarily focuses on cross-platform software installed within the user space.
> 
>     2. `oma` is more suitable for global installations.
> 
>     3. oma is provided in deb form, not portable executable.
> 
> 
> So we introduce oma only to 'x install', not pkg.
> 
> Thank you ~

Thanks!

**Comment by edwinjhlee** [comment]
I am closing this issue. Feel free to reopen this issue if you have related questions or requirements.
