### ISSUE TITLE
["BUG"] x df broken | [mod=df] [v0.4.10]

### ISSUE THREAD

**Issue by drahnieR** [x-cmd/x-cmd#78]
**Describe the bug**
x df broken on MacOS

**System (please complete the following information):**
 - Version: df939bc2198b5d667fde7eae2791f896689a54d658fa6665feb20a5db9053337bea963039589362f6f8d5641057ee249d87c30e8d85b4eaeba169450d50c73b0
 - Shell: Zsh
 - OS: Darwin (MacOS 14.6.1)
 - Arch: amd64

**Screenshots**
```
$ x df
/usr/local/opt/coreutils/libexec/gnubin/df: invalid option -- 'Y'
Try '/usr/local/opt/coreutils/libexec/gnubin/df --help' for more information.
- E|tui: The CSV data is empty.
```

**To Reproduce**
1. Type command: `x df`

**Expected behavior**
an interactive as shown in https://www.x-cmd.com/mod/df

**Comment by drahnieR** [comment]
Just realize I was using df from https://www.gnu.org/software/coreutils/, not the one comes with MacOS. Closing this

**Comment by edwinjhlee** [comment]
That's indeed a problem. Maybe we should figure out a way to identify the current df in the PATH is the df we expect.
If not, we should download the expected df and use it.

**Comment by edwinjhlee** [comment]
Now we are closing this issue because v0.4.10 is released.
