### ISSUE TITLE
[INSTALL] sniffnet

### ISSUE THREAD

**Issue by edwinjhlee** [x-cmd/x-cmd#79]
**Basic Information**

name: snitiffnet
official website: https://sniffnet.net/ 
source code website: https://github.com/GyulyVGC/sniffnet

**meta**:

- license:  Apache-2.0, MIT licenses
- version: v1.3.1

**Does this software function well in Windows, Linux, Mac, for amd64 and arm64**

Yes.

**Describe this software you'd like to recommend**

Application to comfortably monitor your Internet traffic
Cross-platform, Intuitive, Reliable

**Additional context**

None.

**Comment by lunrenyi** [comment]
`sniffnet` is ready.
```sh
x install update
x install sniffnet
```
