### ISSUE TITLE
[PKG] pgcli, mssql-cli, mycli

### ISSUE THREAD

**Issue by edwinjhlee** [x-cmd/x-cmd#80]
**Basic Information**

name: pgcli, mssql-cli, mycli
official website: https://github.com/dbcli
source code website: https://github.com/dbcli

**Does this software function well in Windows, Linux, Mac, for amd64 and arm64**

Yes

**Describe this package you'd like to recommend**

Python powered cli for various db with unified design.

**Additional context**

We already have litecli in x-cmd pkg.

**Comment by lunrenyi** [comment]
pgcli,mssql-cli,mycli is ready.
```sh
x env use pgcli
x env use mssql-cli
x env use mycli
```
