### ISSUE TITLE
["BUG"]mac termux无法使用部分功能

### ISSUE THREAD

**Issue by nagisb2** [x-cmd/x-cmd#81]
**Describe the bug**
输入部分命令会出现/usr/bin/awk: too many -f options

**System :**
 - Version: [.c7d76596, c7d765961ce18be028f3095c5df96b294323f46b2fe58001a4722cd418f8baddbc5ef0a10e553cbfd7815ff99ab5fdeb052f29552998d64373144f9d8bfa6c88]
 - Shell: [ Zsh]
 - OS: [MAC]
 - Arch: [arm64]

**Screenshots**
![](https://github.com/nagisb2/picx-images-hosting/raw/master/mac.webp)

**Expected behavior**

**Additional context**

**Comment by edwinjhlee** [comment]
Wow, 在此之前，我还不知道 termux 可以在 mac 上 跑。

但这个问题我知道。有些老 awk 版本不支持 多个 -f 的参数。但我们非常依赖这个行为进行 awk 的项目管理。
而且我们认为随着时间的 推移，这些 awk 版本 将不再存在。

可以这么解决：

1. 用系统命令 安装一个较新的 awk （ 例如 gawk ）
2. 我建议采用1，但也可以用 x cosmo use awk，这个命令会在 ~/.x-cmd.root/bin 上放一个 awk，而  ~/.x-cmd.root/bin 会在 x-cmd 启动时自动注入到 PATH，此时  awk 命令会优先调用 ~/.x-cmd.root/bin/awk

值得注意，虽然我们对 手机上通过用 termux/ish 使用 x-cmd 很感兴趣 （ https://www.x-cmd.com/start/termux-ish ），但考虑到当前的工作/测试量，以及开发能力，我们只能优先在更为常见的场景。

x-cmd 虽然已在内部使用三年，但是并没有在 termux/ish 上正常使用过。所以，问题应该不少。

**Comment by edwinjhlee** [comment]
另外，能否告诉你在 mac 使用 termux 的方式 ？我们或许可以使之成为我们 在 mac 上调试 x-cmd 在 termux 行为的 方式。

**Comment by edwinjhlee** [comment]
我刚才用 https://github.com/termux/termux-docker 这种方式来快速使用 termux 。里面的 awk 是 gawk，应该不会出现 -f 多次出现的问题。

**Comment by edwinjhlee** [comment]
朋友，再认真看了你的 neofetch 截图，这跟 termux 没关系。

你的 macos 的版本比较旧，里面的 awk 就是没有这个特性。
因为版权问题，mac 没有 采用 gawk，也没有 用 mawk，而且用的 true awk 也是老版本的。不过，稍微新一点版本的 macos 是没有这个问题的。

可以 参考我上面的方法，对 awk 进行升级即可。

**Comment by nagisb2** [comment]
好吧，我使用
