### ISSUE TITLE
[PKG] fastfetch

### ISSUE THREAD

**Issue by edwinjhlee** [x-cmd/x-cmd#83]
**Basic Information**

name: fastfetch
official website: 
source code website: https://github.com/fastfetch-cli/fastfetch

**meta**:

- license: MIT
- version: v2.24.0

**Provide a tldr like example to help us understand**

- x fastfetch
 
**Does this software function well in Windows, Linux, Mac, for amd64 and arm64**

YES. It also works well in freebsd.

**Describe this package you'd like to recommend**

Neofetch alternative. Written in C.

**Comment by curry798** [comment]
fastfetch is ready.

```bash
x fastfetch 
x env use fastfetch 
```
