### ISSUE TITLE
["BUG"] x scoop not found scoop root path in custom installation path

### ISSUE THREAD

**Issue by ricardo-le** [x-cmd/x-cmd#87]
**Describe the bug**

when i use x scoop it throws - E|scoop: |Not found scoop root path ； unable to find configuration item to input the root path

**System (please complete the following information):**
 - Version: 914fcf6e5a8a307e43747c0aaa16e59b51275c1ed47281324439d8d7178d29ff6b6a1e1cf16005fe61296d01fbc00656645624d6b6da1f045e57e31ab44705fb
 - Shell: bash
 - OS:  Windows
 - Arch: amd64

**Screenshots**
![image](https://github.com/user-attachments/assets/4a3739c1-ed0e-4adb-bb61-4156765cdd92)

**To Reproduce**
Use custom installation path when installing Scoop

**Expected behavior**
it will find the scoop root path or ask me the root path

**Comment by qiakai** [comment]
Hi there!

Thank you for your feedback! There are indeed two ways to customize the Scoop root path:

1. You can use `command scoop config root_path <value>` to save your custom root path location.
2. Alternatively, you can set the root path using `___X_CMD_SCOOP_ROOT_PATH=<root path>`, which can be added to your rc file (like .bashrc).

Just a heads up: the path formats for these two methods are different.
Hope this helps!

Example:
![image](https://github.com/user-attachments/assets/a2deee6b-1405-4015-be31-768bf5439ab1)

**Comment by ricardo-le** [comment]
thanks ,I used the first method and it worked
