### ISSUE TITLE
["BUG"] install git error use x-command latest version

### ISSUE THREAD

**Issue by DerickIT** [x-cmd/x-cmd#89]
**Describe the bug**
    source: /home/ec2-user/.x-cmd.root/local/data/pkg/sphere/X/tree.linux.x64.0/fzf/v0.55.0/bin/
    shim_bin: /home/ec2-user/.x-cmd.root/local/data/pkg/sphere/X/tree.linux.x64.0/fzf/v0.55.0/shim_bin/
    adaptive_shim_bin: /home/ec2-user/.x-cmd.root/local/data/pkg/sphere/X/tree.linux.x64.0/fzf/v0.55.0/adaptive_shim_bin/
- I|pkg: fzf v0.55.0 install successfully
- I|install: Selected software -> [git]
- I|install: Running the code
  more:
    code: x open https://git-scm.com/
- E|install: Execute failed
[ec2-user@ip-172-31-0-10 ~]$

**System (please complete the following information):**
 - Version: [A sha512, type 'x version' so you can get the version sum]
 - Shell: [e.g. Dash, Bash, Zsh]
 - OS: [e.g. Linux, Darwin, Windows]
 - Arch: [e.g. amd64, arm64]

**Screenshots**

**To Reproduce**
1. Start up service: '...'
2. Type command: '...'

**Expected behavior**

**Additional context**

**Comment by edwinjhlee** [comment]
<img width="551" alt="image" src="https://github.com/user-attachments/assets/d640b54b-4de1-4d1d-9ca1-112e5c4b9d8d">


`x open  https://git-scm.com/` is design to browse the webpage https://git-scm.com/ for more information.
According to the information you provided, it was in the server environment so opening browser is unavailable.

In the future:
- We will add more information about 'x open ...'
- Disable this option if it is unavailable.

**Comment by DerickIT** [comment]
Yes, I am currently unable to install git with either option

**Comment by edwinjhlee** [comment]
@DerickIT 

You can try use `x pixi global install git` .

Later we will add pixi installation in `x install` .
