### ISSUE TITLE
-bash: BASH_COMPLETION_COMPAT_DIR: readonly variable["BUG"]

### ISSUE THREAD

**Issue by wangfeng-ux** [x-cmd/x-cmd#9]
exec  eval "$(curl https://get.x-cmd.com)": -bash: BASH_COMPLETION_COMPAT_DIR: readonly variable
-bash: x: command not found

**Comment by edwinjhlee** [comment]
这个问题 大致 判断是 ：

1. BASH_COMPLETION_COMPAT_DIR 这个变量 在环境中 被 设定为 readonly
2. 这个变量应该是 BASH_COMPLETION 框架中用到了，然后触发了错误退出
3. x-cmd 的 在命令补全 体系用的是 advise 模块，但现在因为补全的命令总量还不够，因此用到了BASH 和 ZSH 的 completion 框架，因此在交互启动时，会加载 BASH_COMPLETION 或者 ZSH_COMPLETION -- 也因此增加了 x-cmd 的加载时间。

长远来说（两-三个月内），x-cmd 会在 advise 上最终移除 BASH_COMPLETION/ZSH_COMPLETION。所以这个问题会直接被处理。

但当前的解决的方法，可能是:
1. 需要一种办法来 将这个环境 变得 适合 加载 BASH_COMPLETION
2. disable 掉 BASH_COMPLEITION

另外，关于 `exec eval "$(curl https://get.x-cmd.com/)"` 这种使用方式我们之前也没有尝试过，我们还需要时间做实验了解这种方式在行为特点。

**Comment by wangfeng-ux** [comment]
> 这个问题 大致 判断是 ：
> 
> 1. BASH_COMPLETION_COMPAT_DIR 这个变量 在环境中 被 设定为 readonly
> 2. 这个变量应该是 BASH_COMPLETION 框架中用到了，然后触发了错误退出
> 3. x-cmd 的 在命令补全 体系用的是 advise 模块，但现在因为补全的命令总量还不够，因此用到了BASH 和 ZSH 的 completion 框架，因此在交互启动时，会加载 BASH_COMPLETION 或者 ZSH_COMPLETION -- 也因此增加了 x-cmd 的加载时间。
> 
> 长远来说（两-三个月内），x-cmd 会在 advise 上最终移除 BASH_COMPLETION/ZSH_COMPLETION 以提高启动效率。所以这个问题会不复存在。
> 
> 但当前的解决的方法，可能是:
> 
> 1. 需要一种办法来 将这个环境 变得 适合 加载 BASH_COMPLETION
> 2. disable 掉 BASH_COMPLEITION
> 
> 另外，关于 `exec eval "$(curl https://get.x-cmd.com/)"` 这种使用方式我们之前也没有尝试过，我们还需要时间做实验了解这种方式在行为特点。



> exec eval "$(curl https://get.x-cmd.com)": -bash: BASH_COMPLETION_COMPAT_DIR: readonly variable -bash: x: command not found

**Comment by wangfeng-ux** [comment]
> > 这个问题 大致 判断是 ：
> > 
> > 1. BASH_COMPLETION_COMPAT_DIR 这个变量 在环境中 被 设定为 readonly
> > 2. 这个变量应该是 BASH_COMPLETION 框架中用到了，然后触发了错误退出
> > 3. x-cmd 的 在命令补全 体系用的是 advise 模块，但现在因为补全的命令总量还不够，因此用到了BASH 和 ZSH 的 completion 框架，因此在交互启动时，会加载 BASH_COMPLETION 或者 ZSH_COMPLETION -- 也因此增加了 x-cmd 的加载时间。
> > 
> > 长远来说（两-三个月内），x-cmd 会在 advise 上最终移除 BASH_COMPLETION/ZSH_COMPLETION 以提高启动效率。所以这个问题会不复存在。
> > 但当前的解决的方法，可能是:
> > 
> > 1. 需要一种办法来 将这个环境 变得 适合 加载 BASH_COMPLETION
> > 2. disable 掉 BASH_COMPLEITION
> > 
> > 另外，关于 `exec eval "$(curl https://get.x-cmd.com/)"` 这种使用方式我们之前也没有尝试过，我们还需要时间做实验了解这种方式在行为特点。
> 
> > exec eval "$(curl https://get.x-cmd.com)": -bash: BASH_COMPLETION_COMPAT_DIR: readonly variable -bash: x: command not found

是的，刚探索了一下解决方案
在 ~/.bash_profile 或者 ~/,bashrc尾部追加
```
unset BASH_COMPLETION_COMPAT_DIR >/dev/null 2>&1
if [ $? -ne 0 ]; then
   gdb <<EOF
 attach $$
 call unbind_variable("BASH_COMPLETION_COMPAT_DIR")
 detach
 quit
 EOF
 fi
```
随后`source ~/.bash_profile `
最后重新执行  `exec eval "$(curl https://get.x-cmd.com/)"`

**Comment by padparadsayc** [comment]
> 用到了 gdb 的 hack 我对你的环境很感兴趣:

之所以使用 gdb 应该是看的 stackoverflow 上的 [Unset readonly variable in bash](https://stackoverflow.com/questions/17397069/unset-readonly-variable-in-bash) 方案。

不过我也很好奇，你之前是否有装过什么环境，以至于这个变量被声明为了 readonly ，还是说系统装好后就已经是这样了。能否提供更多信息以供我们后续可以更好地应对此类问题？

- 什么发行版
- 什么桌面环境
- bash_profile 在 x-cmd 之前加载了什么

@wangfeng-ux

**Comment by qiakai** [comment]
已更新了 bash-completion 资源包，取消使用 BASH_COMPLETION_COMPAT_DIR 变量。

如果可以使用 x 命令，在 bash 环境 手动执行  `x advise man update completion` 更新资源包即可。
后续 eval $(curl https://get.x-cmd.com) 就不再需要额外处理 BASH_COMPLETION_COMPAT_DIR 变量了。
@wangfeng-ux

**Comment by wangfeng-ux** [comment]
> 用到了 gdb 的 hack 我对你的环境很感兴趣:
> 
> 1. 为什么要用 `exec eval "$(curl https://get.x-cmd.com/)"` ，按照这个写法，这里的 eval 应该是一个外部命令，而不是我们原设计期待的 shell 内部命令 eval
> 2. 在 bash_profile 上之前是加载了什么了吗？所以导致了 这个变量 被 声明 readonly ？
> 
> 这个环境是不是团队内部的受限环境？出于安全，所以在启动前对一批环境变量进行了禁用 ？并且对 eval 进行了包装 ？

不好意思，这里笔误，`eval "$(curl https://get.x-cmd.com/)"`，正常执行

**Comment by wangfeng-ux** [comment]
> > 用到了 gdb 的 hack 我对你的环境很感兴趣:
> 
> 之所以使用 gdb 应该是看的 stackoverflow 上的 [Unset readonly variable in bash](https://stackoverflow.com/questions/17397069/unset-readonly-variable-in-bash) 方案。
> 
> 不过我也很好奇，你之前是否有装过什么环境，以至于这个变量被声明为了 readonly ，还是说系统装好后就已经是这样了。能否提供更多信息以供我们后续可以更好地应对此类问题？
> 
> * 什么发行版
> * 什么桌面环境
> * bash_profile 在 x-cmd 之前加载了什么
> 
> @wangfeng-ux

> * 什么发行版本
```
uname -a
Linux drivers.team 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
> * 什么桌面环境
没有桌面环境吧，`echo $XDG_CURRENT_DESKTOP` 值为空

> * bash_profile 在 x-cmd 之前加载了什么
没有加载什么，应该是系统加载好就这样了；每次开启新的终端，BASH_COMPLETION_COMPAT_DIR 都会恢复成原来的值`/etc/bash_completion.d`

**Comment by wangfeng-ux** [comment]
> 已更新了 bash-completion 资源包，取消使用 BASH_COMPLETION_COMPAT_DIR 变量。
> 
> 如果可以使用 x 命令，在 bash 环境 手动执行 `x advise man update completion` 更新资源包即可。 后续 eval $(curl https://get.x-cmd.com) 就不再需要额外处理 BASH_COMPLETION_COMPAT_DIR 变量了。 @wangfeng-ux

已更新资源包，问题已解决，感谢大佬 :+1:
