### ISSUE TITLE
["BUG"] apt补全失效 | [mod=advise] [v0.4.14]

### ISSUE THREAD

**Issue by 0LEL0** [x-cmd/x-cmd#93]
**Describe the bug**
在我安装x-cmd工具后apt install无法使用Tab进行包的名字补全了，我尝试使用了x apt install也没有效果。

**System (please complete the following information):**
 - Version: [df939bc2198b5d667fde7eae2791f896689a54d658fa6665feb20a5db9053337bea963039589362f6f8d5641057ee249d87c30e8d85b4eaeba169450d50c73b0]
 - Shell: [Zsh]
 - OS: [Ubuntu22.04]
 - Arch: [amd64]

**To Reproduce**
1. 输入 apt install openj
2. 按下tab

**Expected behavior**
应该会自动提示补全包名，但在x-cmd安装后没有了。

**Comment by edwinjhlee** [comment]
我们 在 advise/补全 上可能有些 bug。我们 v0.4.12 应该已经做了 一些 fix。
后面在 v0.4.13 我们再重新审视一下我们的补全和系统已有补全之间的关系。然后提供一些命令来方便控制其行为。

当前情况下，你可以通过 在 zshrc 文件中，在 x-cmd 加载前 先 `export ___X_CMD_ADVISE_DISABLE=1`， 以此 disable x-cmd 自带的 completion。

**Comment by edwinjhlee** [comment]
我们改善了 advise 的加载行为，如果环境已加载 zsh-completion 或者 bash-complettion，x-cmd 只会启动对 x-cmd 引入命令的补全，不引入其它命令的补全。

计划在周一发布 v0.4.13，周三切换到 latest 。

**Comment by edwinjhlee** [comment]
同时，我们也会修复 自带的 apt install 的补全。

**Comment by 0LEL0** [comment]
我更新到了version: v0.4.13，但apt install的补全还是有问题，我也尝试了卸载重装也没有解决

**Comment by edwinjhlee** [comment]
> 我更新到了version: v0.4.13，但apt install的补全还是有问题，我也尝试了卸载重装也没有解决

好，我们再看看哈 ～

**Comment by 0LEL0** [comment]
好的

**Comment by lunrenyi** [comment]
@0LEL0 我们已经发布了 v0.4.14 的 alpha 版本，其中修复了 apt install 的补全问题 🎉

```sh
x upgrade alpha
apt install openjd<tab>
```
<img width="960" alt="image" src="https://github.com/user-attachments/assets/560503d0-6ba9-4ebc-9bfa-9d4b2458be00">
