### ISSUE TITLE
["BUG"]使用x fastfetch时候无法正确下载

### ISSUE THREAD

**Issue by KuRRe8** [x-cmd/x-cmd#97]
**Describe the bug**
使用x fastfetch时候下载完毕报错file corrupted

**System (please complete the following information):**
 - Version: [914fcf6e5a8a307e43747c0aaa16e59b51275c1ed47281324439d8d7178d29ff6b6a1e1cf16005fe61296d01fbc00656645624d6b6da1f045e57e31ab44705fb]
 - Shell: [Bash]
 - OS: [RHEL]
 - Arch: [amd64]

**Screenshots**
![image](https://github.com/user-attachments/assets/19438eb8-713d-4ffa-b289-445841463e8e)

**To Reproduce**
1. Start up service: '...'
2. Type command: '...'

**Expected behavior**

**Additional context**

**Comment by edwinjhlee** [comment]
OK ～ 我们跟进一下。不好意思。

**Comment by lunrenyi** [comment]
Thanks for your feedback. We've fixed it! 
You can fix this error by running the following command.
```sh
x pkg update
x fastfetch
```

**Comment by KuRRe8** [comment]
> Thanks for your feedback. We've fixed it! You can fix this error by running the following command.
> 
> ```shell
> x pkg update
> x fastfetch
> ```

it works, thanks a lot
