### ISSUE TITLE
[FEATURE] load packages from a mirror instead of registry.npmjs.org | [v0.4.14]

### ISSUE THREAD

**Issue by jia2** [x-cmd/x-cmd#98]
**Describe the feature**
Due to enterprise firewall, I could not load packages from registry.npmjs.org. It would be nice to configure a mirror to load packages instead of the default site registry.npmjs.org.

**Additional context**
provide a configuration option to set another site to load packages

**Comment by lunrenyi** [comment]
Hi, you can set the environment variable `___X_CMD_PKG_DOWNLOAD_SOURCE` to change the download source. We currently offer two download sources: npm and GitHub. 

```sh
___X_CMD_PKG_DOWNLOAD_SOURCE=github x env use rg

# or .zshrc | .bashrc add item:
export ___X_CMD_PKG_DOWNLOAD_SOURCE=github
```

![CleanShot 2024-10-28 at 17 13 00@2x](https://github.com/user-attachments/assets/e177cef3-2786-4790-90dd-409267e47f9e)

**Comment by edwinjhlee** [comment]
In the next version, outside of mainland China, we will use GitHub by default.

**Comment by jia2** [comment]
> Hi, you can set the environment variable `___X_CMD_PKG_DOWNLOAD_SOURCE` to change the download source. We currently offer two download sources: npm and GitHub.
> 
> ```shell
> ___X_CMD_PKG_DOWNLOAD_SOURCE=github x env use rg
> 
> # or .zshrc | .bashrc add item:
> export ___X_CMD_PKG_DOWNLOAD_SOURCE=github
> ```
> 
> ![CleanShot 2024-10-28 at 17 13 00@2x](https://private-user-images.githubusercontent.com/87307989/380648661-e177cef3-2786-4790-90dd-409267e47f9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMTE5MTEsIm5iZiI6MTczMDExMTYxMSwicGF0aCI6Ii84NzMwNzk4OS8zODA2NDg2NjEtZTE3N2NlZjMtMjc4Ni00NzkwLTkwZGQtNDA5MjY3ZTQ3ZjllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDEwMzMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4YWI0MTQ1ZGQwMDM4MWJlNTJiZGI4Mjc0Y2MxN2U3NjE3YzRiZmU2YWYxMGZiMzVhMjAzZDFiOTBmYTNhNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eAYEQceybVV30nSErpTOCb_32xVppK4ALJfX0PcnfeY)

Thanks a lot. It really helps! :)

**Comment by jia2** [comment]
Thanks for your great work!

**Comment by edwinjhlee** [comment]
In the v0.4.14, outside of mainland China, we use GitHub by default.

I am closing this issue. If any related problems occured, feel free to reopen or create a new issue.

Thank you ~ @jia2
