### ISSUE TITLE
["BUG"] win11下msys2下安装x-cmd失败

### ISSUE THREAD

**Issue by yshuai** [x-cmd/x-cmd#99]
**Describe the bug**
在msys2下用wget和curl都安装失败了。都报证书错误。我能从命令行的链接直接下载下来latest.tgz，也试过curl加--proxy 和--socks5，都失败了

![image](https://github.com/user-attachments/assets/3424aa4e-d6a3-4ad1-88dd-e534a244266b)
![image](https://github.com/user-attachments/assets/cdb88637-df98-4fbb-9a87-175fb4a0ee69)

**System (please complete the following information):**
 - Version: win11 专业版23H2
 - Shell: Bash, Zsh
 - OS: Windows11
 - Arch: amd64

**Comment by edwinjhlee** [comment]
> 原来是因为防火墙，关闭防火墙后解决了。

这样不太好。。。

------

应该是系统环境不认 let-encrypt 的证书。这个在早期 alpine 系统上碰到过类似的。

这个问题暂时没有较好的解决思路。我后面花钱换一个 商用的证书吧。

**Comment by yshuai** [comment]
我昨天在msys2的终端上装上x-cmd了，但因为装了好几个scoopd、winget、msys2、nushell之类的，打算卸载几个简洁下工具，打算重装 x-cmd，手动删除了.x-cmd.root文件夹和.bashrc、.zshrc 下的x-cmd代码，但是现在装不上了。报错如下日志，我看了下是安装的时候目录中的时间的`:`不见了， 现在下载到本地的文件的名字是这个 `latest.1811.2024-10-29_095450`，
```
[2024-10-29/09:55:56] Download script archieve from https://oss.resource.x-cmd.com/x-cmd/release/dist/latest.tgz
[2024-10-29/09:55:56] Download SUCCESS: /home/ys/.x-cmd.root/v/latest.1811.2024-10-29_09:55:56/download_tmp.tgz ( size: 1549.08 KB )
[2024-10-29/09:55:57] Deflation SUCCESS: /home/ys/.x-cmd.root/v/latest.1811.2024-10-29_09:55:56/download_tmp.tgz
[2024-10-29/09:55:57] Fail to get version sum from: /home/ys/.x-cmd.root/v/latest.1811.2024-10-29_09:55:56/.x-cmd/metadata/version_sum
```

**Comment by qiakai** [comment]
看一下这个文件里面的内容
```
\cat /home/ys/.x-cmd.root/v/latest.1811.2024-10-29_09:55:56/.x-cmd/metadata/version_sum
```

**Comment by yshuai** [comment]
> 6

在我这win11、msys2环境里，这个文件夹是个空目录。
![image](https://github.com/user-attachments/assets/6b668b19-4f2f-4d28-905d-b463377da86e)

**Comment by yshuai** [comment]
> 看一下这个文件里面的内容以及权限
> 
> ```
> ls -lah /home/ys/.x-cmd.root/v/latest.1811.2024-10-29_09:55:56/.x-cmd/metadata/version_sum
> \cat /home/ys/.x-cmd.root/v/latest.1811.2024-10-29_09:55:56/.x-cmd/metadata/version_sum
> ```

> 
> 在我这win11、msys2环境里，这个文件夹是个空目录，猜测是因为改名前的某步骤出问题了，现在`:`变成多个空格了 。

![image](https://github.com/user-attachments/assets/14b8fd30-30d3-486c-a68a-06ff24648316)

![image](https://github.com/user-attachments/assets/2d9db70b-4048-46dd-8943-57eac7cf9120)

**Comment by edwinjhlee** [comment]
哦，那明白了。有冒号，msys2会自动转空格。

**Comment by edwinjhlee** [comment]
@yshuai 我们先绕过了这个问题，直接避免了 : 

不过最好我们还是要搞清楚为什么会自动改 `:` 为 ` ` 。一般这种情况是在 msys2 进行 PATH 传递时才会碰到。当初设计时认为不会在安装时触发，同时为了日志可读性，因此保留了 `:`

**Comment by edwinjhlee** [comment]
@yshuai 麻烦你现在再试一下安装 x-cmd 。

**Comment by yshuai** [comment]
> @yshuai 麻烦你现在再试一下安装 x-cmd 。

我尝试了两遍，文件夹名没问题了，但是那个文件夹还是空的。
然后在`v`文件夹的同级目录也有一个`setup.log`，不知道是两个`setup.log`，还是检测路径错误了？ 具体的如图所示

![image](https://github.com/user-attachments/assets/76d1def1-4eb6-443e-bac3-b5f39fdb0491)

**Comment by yshuai** [comment]
我之前刚卸载了git-bash,用的msys2的终端，因为听说msys2是更完备的linux工具链，以后也打算使用msys2+windows terminal组合，我还以为msys2、git-bash区别不大呢，然后你说了以后，我又安装了git-bash，从git-bash上安装成功了，msys2还不支持吗?

[setup.log](https://github.com/user-attachments/files/17558427/setup.log)

**Comment by edwinjhlee** [comment]
msys 和 git-bash 的关系很复杂。x-cmd 的实现是基于最小的假设进行，很道理应该能运行。

不过，如果你没有对 msys2 进行配置，那么显然，会有一些假设可能不成立，从而导致 x-cmd 的错误。

我们当前对于 windows 的测试更倾向于常用的 git-bash 以及 wsl。msys2 以前测试过，但并没有长期关注和使用。

现在看来，可能 msys2 那边有一些我们没有考虑到的情况（例如，可能 tar 对 gzip 的解压可能不能用），我们找个时间再看看。

**Comment by yshuai** [comment]
好的，谢谢
